// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project f7de02364badfaa1 "Roku_ClientHandoff (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * 'en'
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'outline_gray' | 'outline_brand' | 'fill_brand' | 'fill_gray' | 'fill_brand_without hover' | 'Variant 6' // Variant
 * icon?: undefined // Icon
}} Props

 */
import { stdin_default } from "../chunks/chunk-4WWMVTO5.js";
import { routes } from "../chunks/chunk-VAWW4KIH.js";

// virtual:butt/circle
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/j7IQ1kYjR2Aiynf2lSl2/c7ztituWI9fFrqSUF4si/k8sWGmJY6.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	Instance,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var enabledGestures = {
	ccT12YqkP: {
		hover: true,
	},
	haUn_4Djd: {
		hover: true,
	},
	UpRmQlpuY: {
		hover: true,
	},
	X2578Eect: {
		hover: true,
	},
	YBs2r2JY1: {
		hover: true,
	},
};
var cycleOrder = [
	"haUn_4Djd",
	"X2578Eect",
	"ccT12YqkP",
	"YBs2r2JY1",
	"WQsnvv1xQ",
	"UpRmQlpuY",
];
var serializationHash = "framer-FrVLM";
var variantClassNames = {
	ccT12YqkP: "framer-v-166lbse",
	haUn_4Djd: "framer-v-1hp5rf9",
	UpRmQlpuY: "framer-v-9vjdkn",
	WQsnvv1xQ: "framer-v-1o05m80",
	X2578Eect: "framer-v-a3qb8g",
	YBs2r2JY1: "framer-v-1utdz8y",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 75,
	delay: 0,
	mass: 1,
	stiffness: 500,
	type: "spring",
};
var transformTemplate1 = (_, t) => `translate(-50%, -50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"fill_brand_without hover": "WQsnvv1xQ",
	"Variant 6": "UpRmQlpuY",
	fill_brand: "ccT12YqkP",
	fill_gray: "YBs2r2JY1",
	outline_brand: "X2578Eect",
	outline_gray: "haUn_4Djd",
};
var getProps = ({ height, icon, id, width, ...props }) => {
	return {
		...props,
		suEvguk_q: icon ?? props.suEvguk_q ?? stdin_default,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "haUn_4Djd",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, suEvguk_q, ...restProps } =
		getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "haUn_4Djd",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1hp5rf9",
							className,
							classNames,
						)}
						data-border={true}
						data-framer-name={"outline_gray"}
						layoutDependency={layoutDependency}
						layoutId={"haUn_4Djd"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-3683047d-0b93-4b8d-aaa6-3104c798dfeb, rgb(213, 215, 218))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							backgroundColor: "rgba(0, 0, 0, 0)",
							borderBottomLeftRadius: 100,
							borderBottomRightRadius: 100,
							borderTopLeftRadius: 100,
							borderTopRightRadius: 100,
							...style,
						}}
						variants={{
							"ccT12YqkP-hover": {
								backgroundColor:
									"var(--token-a096d81a-91db-425a-b2a9-ca48ac283707, rgb(255, 255, 255))",
							},
							"haUn_4Djd-hover": {
								"--border-color":
									"var(--token-10e900e6-2b0e-4f3a-9241-1d67cf11b555, rgb(255, 129, 10))",
								backgroundColor: "rgba(0, 0, 0, 0)",
							},
							"UpRmQlpuY-hover": {
								backgroundColor:
									"var(--token-329a9c83-6672-4c88-8eb4-e318446a9640, rgb(248, 80, 23))",
							},
							"X2578Eect-hover": {
								backgroundColor:
									"var(--token-10e900e6-2b0e-4f3a-9241-1d67cf11b555, rgb(255, 129, 10))",
							},
							"YBs2r2JY1-hover": {
								"--border-color":
									"var(--token-e151dd1b-3011-4af4-b6a1-16337cf14949, rgb(0, 0, 0))",
								backgroundColor:
									"var(--token-e151dd1b-3011-4af4-b6a1-16337cf14949, rgb(0, 0, 0))",
							},
							ccT12YqkP: {
								"--border-bottom-width": "0px",
								"--border-left-width": "0px",
								"--border-right-width": "0px",
								"--border-top-width": "0px",
								backgroundColor:
									"var(--token-97b5a5bf-7f90-4453-a989-27caa6d81314, rgb(58, 103, 90))",
							},
							UpRmQlpuY: {
								"--border-bottom-width": "0px",
								"--border-left-width": "0px",
								"--border-right-width": "0px",
								"--border-top-width": "0px",
								backgroundColor:
									"var(--token-9a96d3fa-fe16-4210-b1eb-731a6b45d9ca, rgb(250, 106, 46))",
							},
							WQsnvv1xQ: {
								"--border-bottom-width": "0px",
								"--border-left-width": "0px",
								"--border-right-width": "0px",
								"--border-top-width": "0px",
								backgroundColor:
									"var(--token-97b5a5bf-7f90-4453-a989-27caa6d81314, rgb(58, 103, 90))",
							},
							X2578Eect: {
								"--border-color":
									"var(--token-10e900e6-2b0e-4f3a-9241-1d67cf11b555, rgb(255, 129, 10))",
							},
							YBs2r2JY1: {
								backgroundColor:
									"var(--token-a096d81a-91db-425a-b2a9-ca48ac283707, rgb(255, 255, 255))",
							},
						}}
						{...addPropertyOverrides(
							{
								"ccT12YqkP-hover": {
									"data-framer-name": void 0,
								},
								"haUn_4Djd-hover": {
									"data-framer-name": void 0,
								},
								"UpRmQlpuY-hover": {
									"data-framer-name": void 0,
								},
								"X2578Eect-hover": {
									"data-framer-name": void 0,
								},
								"YBs2r2JY1-hover": {
									"data-framer-name": void 0,
								},
								ccT12YqkP: {
									"data-framer-name": "fill_brand",
								},
								UpRmQlpuY: {
									"data-framer-name": "Variant 6",
								},
								WQsnvv1xQ: {
									"data-framer-name": "fill_brand_without hover",
								},
								X2578Eect: {
									"data-framer-name": "outline_brand",
								},
								YBs2r2JY1: {
									"data-framer-name": "fill_gray",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<Instance
							animated={true}
							className={"framer-62ga1m"}
							Component={suEvguk_q}
							layoutDependency={layoutDependency}
							layoutId={"C6feqYgVo"}
							style={{
								"--1prn4g3":
									"var(--token-67ca5fa7-a56e-420c-a780-e11145832d94, rgb(164, 167, 174))",
								rotate: 0,
							}}
							transformTemplate={transformTemplate1}
							variants={{
								"ccT12YqkP-hover": {
									"--1prn4g3":
										"var(--token-10e900e6-2b0e-4f3a-9241-1d67cf11b555, rgb(75, 129, 112))",
								},
								"haUn_4Djd-hover": {
									"--1prn4g3":
										"var(--token-10e900e6-2b0e-4f3a-9241-1d67cf11b555, rgb(255, 129, 10))",
								},
								"UpRmQlpuY-hover": {
									rotate: 26,
								},
								"X2578Eect-hover": {
									"--1prn4g3":
										"var(--token-a096d81a-91db-425a-b2a9-ca48ac283707, rgb(255, 255, 255))",
								},
								"YBs2r2JY1-hover": {
									"--1prn4g3":
										"var(--token-a096d81a-91db-425a-b2a9-ca48ac283707, rgb(255, 255, 255))",
								},
								ccT12YqkP: {
									"--1prn4g3":
										"var(--token-a096d81a-91db-425a-b2a9-ca48ac283707, rgb(255, 255, 255))",
								},
								UpRmQlpuY: {
									"--1prn4g3":
										"var(--token-a096d81a-91db-425a-b2a9-ca48ac283707, rgb(255, 255, 255))",
								},
								WQsnvv1xQ: {
									"--1prn4g3":
										"var(--token-a096d81a-91db-425a-b2a9-ca48ac283707, rgb(255, 255, 255))",
								},
								X2578Eect: {
									"--1prn4g3":
										"var(--token-10e900e6-2b0e-4f3a-9241-1d67cf11b555, rgb(255, 129, 10))",
								},
								YBs2r2JY1: {
									"--1prn4g3":
										"var(--token-7e83bec4-73bd-4dcd-b0c4-908ed6b9fc9e, rgb(113, 118, 128))",
								},
							}}
						/>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-FrVLM.framer-1ty77fo, .framer-FrVLM .framer-1ty77fo { display: block; }",
	".framer-FrVLM.framer-1hp5rf9 { cursor: pointer; height: 32px; overflow: hidden; position: relative; width: 32px; will-change: var(--framer-will-change-override, transform); }",
	".framer-FrVLM .framer-62ga1m { aspect-ratio: 1 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 16px); left: 50%; position: absolute; top: 50%; width: 16px; }",
	".framer-FrVLM.framer-v-a3qb8g.framer-1hp5rf9, .framer-FrVLM.framer-v-166lbse.framer-1hp5rf9, .framer-FrVLM.framer-v-1utdz8y.framer-1hp5rf9, .framer-FrVLM.framer-v-1hp5rf9.hover.framer-1hp5rf9 { aspect-ratio: 1 / 1; height: var(--framer-aspect-ratio-supported, 32px); }",
	".framer-FrVLM.framer-v-166lbse .framer-62ga1m, .framer-FrVLM.framer-v-1o05m80 .framer-62ga1m { height: var(--framer-aspect-ratio-supported, 12px); width: 12px; }",
	".framer-FrVLM.framer-v-1o05m80.framer-1hp5rf9 { aspect-ratio: 1 / 1; cursor: unset; height: var(--framer-aspect-ratio-supported, 32px); }",
	".framer-FrVLM.framer-v-9vjdkn.framer-1hp5rf9 { aspect-ratio: 1 / 1; height: var(--framer-aspect-ratio-supported, 60px); width: 60px; }",
	".framer-FrVLM.framer-v-9vjdkn .framer-62ga1m { height: var(--framer-aspect-ratio-supported, 24px); width: 24px; }",
	'.framer-FrVLM[data-border="true"]::after, .framer-FrVLM [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var Framerk8sWGmJY6 = withCSS(Component, css, "framer-FrVLM");
var stdin_default2 = Framerk8sWGmJY6;
Framerk8sWGmJY6.displayName = "Butt/Circle";
Framerk8sWGmJY6.defaultProps = {
	height: 32,
	width: 32,
};
addPropertyControls(Framerk8sWGmJY6, {
	variant: {
		options: [
			"haUn_4Djd",
			"X2578Eect",
			"ccT12YqkP",
			"YBs2r2JY1",
			"WQsnvv1xQ",
			"UpRmQlpuY",
		],
		optionTitles: [
			"outline_gray",
			"outline_brand",
			"fill_brand",
			"fill_gray",
			"fill_brand_without hover",
			"Variant 6",
		],
		title: "Variant",
		type: ControlType.Enum,
	},
	suEvguk_q: {
		defaultValue: {
			identifier: "local-module:vector/yFHFS8Ekw:default",
			moduleId: "noleC624femsSwrkNQ4R",
		},
		setModuleId: "xnJUhTduq1GwvR2ilAbr",
		title: "Icon",
		type: ControlType.VectorSetItem,
	},
});
addFonts(
	Framerk8sWGmJY6,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:butt/circle
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [
	{
		id: "bvzy1WeYw",
		name: "English",
		slug: "en",
		code: "en",
	},
];
var defaultResponsiveVariants = {
	base: "UpRmQlpuY",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"f7de02364badfaa19730b887fe40769babb999f1ad18406989d28f58b996eb79"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders CircleFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"f7de02364badfaa19730b887fe40769babb999f1ad18406989d28f58b996eb79"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var circle_default = ComponentWithRoot;
export { circle_default as default };
