// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project f7de02364badfaa1 "Roku_ClientHandoff (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * 'en'
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Variant 1' | 'Variant 2' | 'Variant 3' // Variant
}} Props

 */
import { stdin_default, stdin_default2 } from "../chunks/chunk-BI7CDTOH.js";
import { routes } from "../chunks/chunk-VAWW4KIH.js";

// virtual:faq/icon-circle
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/r5oLcrFwc5W78I6yu7fq/SlwIY3eIoby8oOVpgSiO/LwPLG2i5I.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFonts,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var PlusFonts = getFonts(stdin_default2);
var MinusFonts = getFonts(stdin_default);
var enabledGestures = {
	U4xc_CElV: {
		hover: true,
	},
	zmCb1mPqY: {
		hover: true,
	},
};
var cycleOrder = ["zmCb1mPqY", "U4xc_CElV", "GE2H_IL09"];
var serializationHash = "framer-OnwiZ";
var variantClassNames = {
	GE2H_IL09: "framer-v-90egd3",
	U4xc_CElV: "framer-v-78i7rc",
	zmCb1mPqY: "framer-v-jirqkv",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transformTemplate1 = (_, t) => `translate(-50%, -50%) ${t}`;
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Variant 1": "zmCb1mPqY",
	"Variant 2": "U4xc_CElV",
	"Variant 3": "GE2H_IL09",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "zmCb1mPqY",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "zmCb1mPqY",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-jirqkv",
							className,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"zmCb1mPqY"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-2a5ef645-a3a4-4c5f-ba45-e629298b1709, rgb(1, 0, 5))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							backgroundColor: "rgba(0, 0, 0, 0)",
							borderBottomLeftRadius: 50,
							borderBottomRightRadius: 50,
							borderTopLeftRadius: 50,
							borderTopRightRadius: 50,
							...style,
						}}
						variants={{
							"U4xc_CElV-hover": {
								backgroundColor:
									"var(--token-e151dd1b-3011-4af4-b6a1-16337cf14949, rgb(0, 0, 0))",
							},
							"zmCb1mPqY-hover": {
								backgroundColor:
									"var(--token-e151dd1b-3011-4af4-b6a1-16337cf14949, rgb(0, 0, 0))",
							},
							GE2H_IL09: {
								"--border-bottom-width": "0px",
								"--border-left-width": "0px",
								"--border-right-width": "0px",
								"--border-top-width": "0px",
								backgroundColor:
									"var(--token-e151dd1b-3011-4af4-b6a1-16337cf14949, rgb(0, 0, 0))",
							},
						}}
						{...addPropertyOverrides(
							{
								"U4xc_CElV-hover": {
									"data-framer-name": void 0,
								},
								"zmCb1mPqY-hover": {
									"data-framer-name": void 0,
								},
								GE2H_IL09: {
									"data-framer-name": "Variant 3",
								},
								U4xc_CElV: {
									"data-framer-name": "Variant 2",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						{_jsx(stdin_default2, {
							animated: true,
							className: "framer-7b2ms0",
							layoutDependency,
							layoutId: "QHw5VrUje",
							style: {
								"--1g0o5tb":
									"var(--token-2a5ef645-a3a4-4c5f-ba45-e629298b1709, rgb(1, 0, 5))",
								opacity: 1,
								rotate: 0,
							},
							variants: {
								"zmCb1mPqY-hover": {
									"--1g0o5tb":
										"var(--token-a096d81a-91db-425a-b2a9-ca48ac283707, rgb(255, 255, 255))",
									opacity: 1,
									rotate: 0,
								},
								GE2H_IL09: {
									"--1g0o5tb":
										"var(--token-a096d81a-91db-425a-b2a9-ca48ac283707, rgb(255, 255, 255))",
									opacity: 1,
									rotate: 0,
								},
								U4xc_CElV: {
									opacity: 0,
									rotate: 90,
								},
							},
						})}
						{_jsx(stdin_default, {
							animated: true,
							className: "framer-1tl29ld",
							layoutDependency,
							layoutId: "q7pesHXqQ",
							style: {
								"--1g0o5tb":
									"var(--token-2a5ef645-a3a4-4c5f-ba45-e629298b1709, rgb(1, 0, 5))",
								opacity: 0,
							},
							transformTemplate: transformTemplate1,
							variants: {
								"U4xc_CElV-hover": {
									"--1g0o5tb":
										"var(--token-a096d81a-91db-425a-b2a9-ca48ac283707, rgb(255, 255, 255))",
								},
								GE2H_IL09: {
									"--1g0o5tb":
										"var(--token-a096d81a-91db-425a-b2a9-ca48ac283707, rgb(255, 255, 255))",
								},
								U4xc_CElV: {
									opacity: 1,
								},
							},
						})}
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-OnwiZ.framer-1w23g9w, .framer-OnwiZ .framer-1w23g9w { display: block; }",
	".framer-OnwiZ.framer-jirqkv { cursor: pointer; gap: 16px; height: 48px; overflow: var(--overflow-clip-fallback, clip); position: relative; width: 48px; will-change: var(--framer-will-change-override, transform); }",
	".framer-OnwiZ .framer-7b2ms0 { flex: none; height: var(--framer-aspect-ratio-supported, 32px); left: 8px; position: absolute; right: 8px; top: 8px; width: calc(100% - 16px); }",
	".framer-OnwiZ .framer-1tl29ld { flex: none; height: var(--framer-aspect-ratio-supported, 32px); left: 50%; position: absolute; top: 50%; width: 32px; }",
	".framer-OnwiZ.framer-v-90egd3.framer-jirqkv { cursor: unset; }",
	'.framer-OnwiZ[data-border="true"]::after, .framer-OnwiZ [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerLwPLG2i5I = withCSS(Component, css, "framer-OnwiZ");
var stdin_default3 = FramerLwPLG2i5I;
FramerLwPLG2i5I.displayName = "FAQ/Icon Circle";
FramerLwPLG2i5I.defaultProps = {
	height: 48,
	width: 48,
};
addPropertyControls(FramerLwPLG2i5I, {
	variant: {
		options: ["zmCb1mPqY", "U4xc_CElV", "GE2H_IL09"],
		optionTitles: ["Variant 1", "Variant 2", "Variant 3"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerLwPLG2i5I,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...PlusFonts,
		...MinusFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:faq/icon-circle
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [
	{
		id: "bvzy1WeYw",
		name: "English",
		slug: "en",
		code: "en",
	},
];
var defaultResponsiveVariants = {
	base: "GE2H_IL09",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"f7de02364badfaa19730b887fe40769babb999f1ad18406989d28f58b996eb79"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders IconCircleFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"f7de02364badfaa19730b887fe40769babb999f1ad18406989d28f58b996eb79"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var icon_circle_default = ComponentWithRoot;
export { icon_circle_default as default };
