// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project f7de02364badfaa1 "Roku_ClientHandoff (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * 'en'
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Variant 1' | 'Variant 2' // Variant
 * title?: string // Title
 * desription?: string // Desription
 * click?: Function // Click
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
	stdin_default,
} from "../chunks/chunk-RTIEJ47E.js";
import "../chunks/chunk-BI7CDTOH.js";
import { className, css, fonts } from "../chunks/chunk-FNBO5TQO.js";
import { routes } from "../chunks/chunk-VAWW4KIH.js";

// virtual:faq/item
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/zOf0MrL63FkDFNFyQuqa/VlW2PuzYBByJYo769euo/unpw68Hzy.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var FAQIconCircleFonts = getFonts(stdin_default);
var enabledGestures = {
	oQXrtGzL4: {
		hover: true,
	},
};
var cycleOrder = ["oQXrtGzL4", "guqzWnpoP"];
var serializationHash = "framer-HHqGG";
var variantClassNames = {
	guqzWnpoP: "framer-v-77wwd1",
	oQXrtGzL4: "framer-v-ajy3yj",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Variant 1": "oQXrtGzL4",
	"Variant 2": "guqzWnpoP",
};
var getProps = ({ click, desription, height, id, title, width, ...props }) => {
	return {
		...props,
		n8EcG8J9f: click ?? props.n8EcG8J9f,
		Sd0hNO3_y: desription ?? props.Sd0hNO3_y ?? "Desription",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "oQXrtGzL4",
		yZFelfvb7: title ?? props.yZFelfvb7 ?? "Title",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		yZFelfvb7,
		Sd0hNO3_y,
		n8EcG8J9f,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "oQXrtGzL4",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap1o7rpaj = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (n8EcG8J9f) {
			const res = await n8EcG8J9f(...args);
			if (res === false) return false;
		}
	});
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "guqzWnpoP") return true;
		return false;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-ajy3yj",
							className3,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Variant 1"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"oQXrtGzL4"}
						onTap={onTap1o7rpaj}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-4efc64a6-207c-4d82-a4fe-235a43565dac, rgb(16, 19, 35))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							backgroundColor:
								"var(--token-023c0b02-d6e9-49e1-83e1-ac1f4183d641, rgb(234, 236, 245))",
							borderBottomLeftRadius: 20,
							borderBottomRightRadius: 20,
							borderTopLeftRadius: 20,
							borderTopRightRadius: 20,
							...style,
						}}
						{...addPropertyOverrides(
							{
								"oQXrtGzL4-hover": {
									"data-framer-name": void 0,
								},
								guqzWnpoP: {
									"data-framer-name": "Variant 2",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1052h7u"}
							data-framer-name={"Title"}
							layoutDependency={layoutDependency}
							layoutId={"Fxrb_buRf"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1esw7y"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"J9mYgShwQ"}
								text={yZFelfvb7}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-1czmpbj"}
										data-styles-preset={"uo8u5ceXp"}
									>
										{"Blogs and Resources"}
									</motion.p>
								</React.Fragment>
							</RichText>
							<ComponentViewportProvider
								height={48}
								width={"48px"}
								y={
									(componentViewport?.y || 0) +
									0 +
									(((componentViewport?.height || 200) - 0 - 272) / 2 + 0 + 0) +
									112
								}
								{...addPropertyOverrides(
									{
										guqzWnpoP: {
											y:
												(componentViewport?.y || 0) +
												0 +
												(((componentViewport?.height || 200) - 0 - 424) / 2 +
													0 +
													0) +
												112,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<SmartComponentScopedContainer
									className={"framer-q76e5c-container"}
									layoutDependency={layoutDependency}
									layoutId={"acyprSJfI-container"}
									nodeId={"acyprSJfI"}
									rendersWithMotion={true}
									scopeId={"unpw68Hzy"}
								>
									{_jsx(stdin_default, {
										height: "100%",
										id: "acyprSJfI",
										layoutId: "acyprSJfI",
										style: {
											height: "100%",
											width: "100%",
										},
										variant: "zmCb1mPqY",
										width: "100%",
										...addPropertyOverrides(
											{
												"oQXrtGzL4-hover": {
													variant: "GE2H_IL09",
												},
												guqzWnpoP: {
													variant: "U4xc_CElV",
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						</motion.div>
						{isDisplayed() && (
							<motion.div
								className={"framer-1886a8f"}
								data-framer-name={"Description"}
								layoutDependency={layoutDependency}
								layoutId={"m9N5mKnI1"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1xwu7z5"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"ECH8DV3Lo"}
									text={Sd0hNO3_y}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-6qj0qo"}
											data-styles-preset={"PylgTZkRS"}
										>
											{"Blogs and Resources"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
						)}
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-HHqGG.framer-41m42d, .framer-HHqGG .framer-41m42d { display: block; }",
	".framer-HHqGG.framer-ajy3yj { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 1262px; will-change: var(--framer-will-change-override, transform); }",
	".framer-HHqGG .framer-1052h7u { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: visible; padding: 32px; position: relative; width: 100%; }",
	".framer-HHqGG .framer-1esw7y, .framer-HHqGG .framer-1xwu7z5 { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-HHqGG .framer-q76e5c-container { flex: none; height: 48px; position: relative; width: 48px; }",
	".framer-HHqGG .framer-1886a8f { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: visible; padding: 0px 96px 32px 32px; position: relative; width: 100%; }",
	...css2,
	...css,
	'.framer-HHqGG[data-border="true"]::after, .framer-HHqGG [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var Framerunpw68Hzy = withCSS(Component, css3, "framer-HHqGG");
var stdin_default2 = Framerunpw68Hzy;
Framerunpw68Hzy.displayName = "FAQ/Item";
Framerunpw68Hzy.defaultProps = {
	height: 112,
	width: 1262,
};
addPropertyControls(Framerunpw68Hzy, {
	variant: {
		options: ["oQXrtGzL4", "guqzWnpoP"],
		optionTitles: ["Variant 1", "Variant 2"],
		title: "Variant",
		type: ControlType.Enum,
	},
	yZFelfvb7: {
		defaultValue: "Title",
		title: "Title",
		type: ControlType.String,
	},
	Sd0hNO3_y: {
		defaultValue: "Desription",
		displayTextArea: true,
		title: "Desription",
		type: ControlType.String,
	},
	n8EcG8J9f: {
		title: "Click",
		type: ControlType.EventHandler,
	},
});
addFonts(
	Framerunpw68Hzy,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...FAQIconCircleFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:faq/item
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [
	{
		id: "bvzy1WeYw",
		name: "English",
		slug: "en",
		code: "en",
	},
];
var defaultResponsiveVariants = {
	base: "guqzWnpoP",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"f7de02364badfaa19730b887fe40769babb999f1ad18406989d28f58b996eb79"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ItemFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"f7de02364badfaa19730b887fe40769babb999f1ad18406989d28f58b996eb79"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var item_default = ComponentWithRoot;
export { item_default as default };
