// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project f7de02364badfaa1 "Roku_ClientHandoff (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * 'en'
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Variant 1' | 'Variant 2' | 'Variant 3' | 'Variant 4' | 'Variant 5' | 'Variant 6' // Variant
}} Props

 */
import {
	className as className2,
	css as css2,
	fonts as fonts2,
	stdin_default,
} from "../chunks/chunk-RTIEJ47E.js";
import "../chunks/chunk-BI7CDTOH.js";
import { className, css, fonts } from "../chunks/chunk-FNBO5TQO.js";
import { routes } from "../chunks/chunk-VAWW4KIH.js";

// virtual:faq/list
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/4hE8QbEGSsy981DQvFYy/VTjFZYwefuDhdTvLzon8/qgfSEJic5.js
import { jsx as _jsx2, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider as ComponentViewportProvider2,
	ControlType as ControlType2,
	cx as cx2,
	getFonts as getFonts2,
	SmartComponentScopedContainer as SmartComponentScopedContainer2,
	useActiveVariantCallback as useActiveVariantCallback2,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
	withFX,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/1O09Sn1lsD5e6PhOSN7M/iaRvMaXollQN3gFZC48N/unpw68Hzy.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ComponentViewportProvider,
	ControlType,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	RichText,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var FAQIconCircleFonts = getFonts(stdin_default);
var enabledGestures = {
	oQXrtGzL4: {
		hover: true,
	},
};
var cycleOrder = ["oQXrtGzL4", "guqzWnpoP"];
var serializationHash = "framer-HHqGG";
var variantClassNames = {
	guqzWnpoP: "framer-v-77wwd1",
	oQXrtGzL4: "framer-v-ajy3yj",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Variant 1": "oQXrtGzL4",
	"Variant 2": "guqzWnpoP",
};
var getProps = ({ click, desription, height, id, title, width, ...props }) => {
	return {
		...props,
		n8EcG8J9f: click ?? props.n8EcG8J9f,
		Sd0hNO3_y: desription ?? props.Sd0hNO3_y ?? "Desription",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "oQXrtGzL4",
		yZFelfvb7: title ?? props.yZFelfvb7 ?? "Title",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		yZFelfvb7,
		Sd0hNO3_y,
		n8EcG8J9f,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "oQXrtGzL4",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap1o7rpaj = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (n8EcG8J9f) {
			const res = await n8EcG8J9f(...args);
			if (res === false) return false;
		}
	});
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (baseVariant === "guqzWnpoP") return true;
		return false;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-ajy3yj",
							className3,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Variant 1"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"oQXrtGzL4"}
						onTap={onTap1o7rpaj}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-4efc64a6-207c-4d82-a4fe-235a43565dac, rgb(16, 19, 35))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							backgroundColor:
								"var(--token-023c0b02-d6e9-49e1-83e1-ac1f4183d641, rgb(234, 236, 245))",
							borderBottomLeftRadius: 20,
							borderBottomRightRadius: 20,
							borderTopLeftRadius: 20,
							borderTopRightRadius: 20,
							...style,
						}}
						{...addPropertyOverrides(
							{
								"oQXrtGzL4-hover": {
									"data-framer-name": void 0,
								},
								guqzWnpoP: {
									"data-framer-name": "Variant 2",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1052h7u"}
							data-framer-name={"Title"}
							layoutDependency={layoutDependency}
							layoutId={"Fxrb_buRf"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-1esw7y"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"J9mYgShwQ"}
								text={yZFelfvb7}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-1czmpbj"}
										data-styles-preset={"uo8u5ceXp"}
									>
										{"Blogs and Resources"}
									</motion.p>
								</React.Fragment>
							</RichText>
							<ComponentViewportProvider
								height={48}
								width={"48px"}
								y={
									(componentViewport?.y || 0) +
									0 +
									(((componentViewport?.height || 200) - 0 - 272) / 2 + 0 + 0) +
									112
								}
								{...addPropertyOverrides(
									{
										guqzWnpoP: {
											y:
												(componentViewport?.y || 0) +
												0 +
												(((componentViewport?.height || 200) - 0 - 424) / 2 +
													0 +
													0) +
												112,
										},
									},
									baseVariant,
									gestureVariant,
								)}
							>
								<SmartComponentScopedContainer
									className={"framer-q76e5c-container"}
									layoutDependency={layoutDependency}
									layoutId={"acyprSJfI-container"}
									nodeId={"acyprSJfI"}
									rendersWithMotion={true}
									scopeId={"unpw68Hzy"}
								>
									{_jsx(stdin_default, {
										height: "100%",
										id: "acyprSJfI",
										layoutId: "acyprSJfI",
										style: {
											height: "100%",
											width: "100%",
										},
										variant: "zmCb1mPqY",
										width: "100%",
										...addPropertyOverrides(
											{
												"oQXrtGzL4-hover": {
													variant: "GE2H_IL09",
												},
												guqzWnpoP: {
													variant: "U4xc_CElV",
												},
											},
											baseVariant,
											gestureVariant,
										),
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						</motion.div>
						{isDisplayed() && (
							<motion.div
								className={"framer-1886a8f"}
								data-framer-name={"Description"}
								layoutDependency={layoutDependency}
								layoutId={"m9N5mKnI1"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1xwu7z5"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"ECH8DV3Lo"}
									text={Sd0hNO3_y}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-6qj0qo"}
											data-styles-preset={"PylgTZkRS"}
										>
											{"Blogs and Resources"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
						)}
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-HHqGG.framer-41m42d, .framer-HHqGG .framer-41m42d { display: block; }",
	".framer-HHqGG.framer-ajy3yj { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 1262px; will-change: var(--framer-will-change-override, transform); }",
	".framer-HHqGG .framer-1052h7u { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: visible; padding: 32px; position: relative; width: 100%; }",
	".framer-HHqGG .framer-1esw7y, .framer-HHqGG .framer-1xwu7z5 { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-HHqGG .framer-q76e5c-container { flex: none; height: 48px; position: relative; width: 48px; }",
	".framer-HHqGG .framer-1886a8f { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: visible; padding: 0px 96px 32px 32px; position: relative; width: 100%; }",
	...css2,
	...css,
	'.framer-HHqGG[data-border="true"]::after, .framer-HHqGG [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var Framerunpw68Hzy = withCSS(Component, css3, "framer-HHqGG");
var stdin_default2 = Framerunpw68Hzy;
Framerunpw68Hzy.displayName = "FAQ/Item";
Framerunpw68Hzy.defaultProps = {
	height: 112,
	width: 1262,
};
addPropertyControls(Framerunpw68Hzy, {
	variant: {
		options: ["oQXrtGzL4", "guqzWnpoP"],
		optionTitles: ["Variant 1", "Variant 2"],
		title: "Variant",
		type: ControlType.Enum,
	},
	yZFelfvb7: {
		defaultValue: "Title",
		title: "Title",
		type: ControlType.String,
	},
	Sd0hNO3_y: {
		defaultValue: "Desription",
		displayTextArea: true,
		title: "Desription",
		type: ControlType.String,
	},
	n8EcG8J9f: {
		title: "Click",
		type: ControlType.EventHandler,
	},
});
addFonts(
	Framerunpw68Hzy,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...FAQIconCircleFonts,
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/4hE8QbEGSsy981DQvFYy/VTjFZYwefuDhdTvLzon8/qgfSEJic5.js
var FAQItemFonts = getFonts2(stdin_default2);
var SmartComponentScopedContainerWithFX = withFX(
	SmartComponentScopedContainer2,
);
var cycleOrder2 = [
	"g92tKNYmW",
	"H01wOCsaP",
	"YULiI2aDA",
	"oBFKzsOBD",
	"hSCJMr1Bi",
	"OwG1Xm5fX",
];
var serializationHash2 = "framer-XxuLB";
var variantClassNames2 = {
	g92tKNYmW: "framer-v-1lrepgp",
	H01wOCsaP: "framer-v-10nug4j",
	hSCJMr1Bi: "framer-v-izbhbs",
	oBFKzsOBD: "framer-v-1nly8f3",
	OwG1Xm5fX: "framer-v-8a4lu7",
	YULiI2aDA: "framer-v-116c5yj",
};
function addPropertyOverrides2(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition12 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var animation = {
	opacity: 0,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 0.9,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 30,
};
var transition2 = {
	delay: 0.2,
	duration: 0.9,
	ease: [0.22, 0.85, 0.56, 1],
	type: "tween",
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var humanReadableVariantMap2 = {
	"Variant 1": "g92tKNYmW",
	"Variant 2": "H01wOCsaP",
	"Variant 3": "YULiI2aDA",
	"Variant 4": "oBFKzsOBD",
	"Variant 5": "hSCJMr1Bi",
	"Variant 6": "OwG1Xm5fX",
};
var getProps2 = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap2[props.variant] ?? props.variant ?? "g92tKNYmW",
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		cycleOrder: cycleOrder2,
		defaultVariant: "g92tKNYmW",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback2(baseVariant);
	const n8EcG8J9f17rznhp = activeVariantCallback(async (...args) => {
		setVariant("H01wOCsaP");
	});
	const n8EcG8J9f1xmfrwg = activeVariantCallback(async (...args) => {
		setVariant("g92tKNYmW");
	});
	const n8EcG8J9f1up0icd = activeVariantCallback(async (...args) => {
		setVariant("YULiI2aDA");
	});
	const n8EcG8J9fxf5c6q = activeVariantCallback(async (...args) => {
		setVariant("oBFKzsOBD");
	});
	const n8EcG8J9f1vy6ets = activeVariantCallback(async (...args) => {
		setVariant("hSCJMr1Bi");
	});
	const n8EcG8J9f1tdlyiz = activeVariantCallback(async (...args) => {
		setVariant("OwG1Xm5fX");
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.div
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-1lrepgp",
							className3,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"g92tKNYmW"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides2(
							{
								H01wOCsaP: {
									"data-framer-name": "Variant 2",
								},
								hSCJMr1Bi: {
									"data-framer-name": "Variant 5",
								},
								oBFKzsOBD: {
									"data-framer-name": "Variant 4",
								},
								OwG1Xm5fX: {
									"data-framer-name": "Variant 6",
								},
								YULiI2aDA: {
									"data-framer-name": "Variant 3",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<ComponentViewportProvider2
							height={112}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 656) - 0 - 656) / 2 + 0 + 0)
							}
							{...addPropertyOverrides2(
								{
									H01wOCsaP: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 736) - 0 - 656) / 2 +
												0 +
												0),
									},
									hSCJMr1Bi: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 200) - 0 - 656) / 2 +
												0 +
												0),
									},
									oBFKzsOBD: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 200) - 0 - 656) / 2 +
												0 +
												0),
									},
									OwG1Xm5fX: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 200) - 0 - 656) / 2 +
												0 +
												0),
									},
									YULiI2aDA: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 736) - 0 - 656) / 2 +
												0 +
												0),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<SmartComponentScopedContainerWithFX
								__framer__animate={{
									transition: transition2,
								}}
								__framer__animateOnce={true}
								__framer__enter={animation}
								__framer__styleAppearEffectEnabled={true}
								__framer__threshold={0.5}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								className={"framer-wzfnku-container"}
								layoutDependency={layoutDependency}
								layoutId={"yexnW3pt5-container"}
								nodeId={"yexnW3pt5"}
								rendersWithMotion={true}
								scopeId={"qgfSEJic5"}
							>
								{_jsx2(stdin_default2, {
									height: "100%",
									id: "yexnW3pt5",
									layoutId: "yexnW3pt5",
									n8EcG8J9f: n8EcG8J9f17rznhp,
									Sd0hNO3_y:
										"Yes. Roku Bot is fully non-custodial, meaning your funds always stay in your own wallet. All trades are executed on-chain via Solana, so you remain in full control of your assets and private keys at all times.",
									style: {
										width: "100%",
									},
									variant: "oQXrtGzL4",
									width: "100%",
									yZFelfvb7: "Is Roku Bot safe to use?",
									...addPropertyOverrides2(
										{
											H01wOCsaP: {
												n8EcG8J9f: n8EcG8J9f1xmfrwg,
												variant: "guqzWnpoP",
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</SmartComponentScopedContainerWithFX>
						</ComponentViewportProvider2>
						<ComponentViewportProvider2
							height={112}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 656) - 0 - 656) / 2 + 112 + 24)
							}
							{...addPropertyOverrides2(
								{
									H01wOCsaP: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 736) - 0 - 656) / 2 +
												112 +
												24),
									},
									hSCJMr1Bi: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 200) - 0 - 656) / 2 +
												112 +
												24),
									},
									oBFKzsOBD: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 200) - 0 - 656) / 2 +
												112 +
												24),
									},
									OwG1Xm5fX: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 200) - 0 - 656) / 2 +
												112 +
												24),
									},
									YULiI2aDA: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 736) - 0 - 656) / 2 +
												112 +
												24),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<SmartComponentScopedContainerWithFX
								__framer__animate={{
									transition: transition2,
								}}
								__framer__animateOnce={true}
								__framer__enter={animation}
								__framer__styleAppearEffectEnabled={true}
								__framer__threshold={0.5}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								className={"framer-1kc5fdc-container"}
								layoutDependency={layoutDependency}
								layoutId={"DnBRMoD_P-container"}
								nodeId={"DnBRMoD_P"}
								rendersWithMotion={true}
								scopeId={"qgfSEJic5"}
							>
								{_jsx2(stdin_default2, {
									height: "100%",
									id: "DnBRMoD_P",
									layoutId: "DnBRMoD_P",
									n8EcG8J9f: n8EcG8J9f1up0icd,
									Sd0hNO3_y:
										"You can trade any token available on the Solana network as long as there is on-chain liquidity. From popular tokens to new launches, Roku helps you trade them quickly and efficiently.",
									style: {
										width: "100%",
									},
									variant: "oQXrtGzL4",
									width: "100%",
									yZFelfvb7: "What tokens can I trade with Roku?",
									...addPropertyOverrides2(
										{
											YULiI2aDA: {
												n8EcG8J9f: n8EcG8J9f1xmfrwg,
												variant: "guqzWnpoP",
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</SmartComponentScopedContainerWithFX>
						</ComponentViewportProvider2>
						<ComponentViewportProvider2
							height={112}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 656) - 0 - 656) / 2 + 224 + 48)
							}
							{...addPropertyOverrides2(
								{
									H01wOCsaP: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 736) - 0 - 656) / 2 +
												224 +
												48),
									},
									hSCJMr1Bi: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 200) - 0 - 656) / 2 +
												224 +
												48),
									},
									oBFKzsOBD: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 200) - 0 - 656) / 2 +
												224 +
												48),
									},
									OwG1Xm5fX: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 200) - 0 - 656) / 2 +
												224 +
												48),
									},
									YULiI2aDA: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 736) - 0 - 656) / 2 +
												224 +
												48),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<SmartComponentScopedContainerWithFX
								__framer__animate={{
									transition: transition2,
								}}
								__framer__animateOnce={true}
								__framer__enter={animation}
								__framer__styleAppearEffectEnabled={true}
								__framer__threshold={0.5}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								className={"framer-wtqtp2-container"}
								layoutDependency={layoutDependency}
								layoutId={"OZGEi6Ecx-container"}
								nodeId={"OZGEi6Ecx"}
								rendersWithMotion={true}
								scopeId={"qgfSEJic5"}
							>
								{_jsx2(stdin_default2, {
									height: "100%",
									id: "OZGEi6Ecx",
									layoutId: "OZGEi6Ecx",
									n8EcG8J9f: n8EcG8J9fxf5c6q,
									Sd0hNO3_y:
										"Getting started with Roku Bot is quick and simple. Just open Telegram and search for Roku Trade Bot, then type /start to create or import a wallet. After that, deposit SOL into your wallet and you can immediately start trading using commands like /buy or /copy.",
									style: {
										width: "100%",
									},
									variant: "oQXrtGzL4",
									width: "100%",
									yZFelfvb7: "How do I get started with Roku Bot?",
									...addPropertyOverrides2(
										{
											oBFKzsOBD: {
												n8EcG8J9f: n8EcG8J9f1xmfrwg,
												variant: "guqzWnpoP",
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</SmartComponentScopedContainerWithFX>
						</ComponentViewportProvider2>
						<ComponentViewportProvider2
							height={112}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 656) - 0 - 656) / 2 + 336 + 72)
							}
							{...addPropertyOverrides2(
								{
									H01wOCsaP: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 736) - 0 - 656) / 2 +
												336 +
												72),
									},
									hSCJMr1Bi: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 200) - 0 - 656) / 2 +
												336 +
												72),
									},
									oBFKzsOBD: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 200) - 0 - 656) / 2 +
												336 +
												72),
									},
									OwG1Xm5fX: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 200) - 0 - 656) / 2 +
												336 +
												72),
									},
									YULiI2aDA: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 736) - 0 - 656) / 2 +
												336 +
												72),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<SmartComponentScopedContainerWithFX
								__framer__animate={{
									transition: transition2,
								}}
								__framer__animateOnce={true}
								__framer__enter={animation}
								__framer__styleAppearEffectEnabled={true}
								__framer__threshold={0.5}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								className={"framer-imy7yl-container"}
								layoutDependency={layoutDependency}
								layoutId={"VrtVZ1N7a-container"}
								nodeId={"VrtVZ1N7a"}
								rendersWithMotion={true}
								scopeId={"qgfSEJic5"}
							>
								{_jsx2(stdin_default2, {
									height: "100%",
									id: "VrtVZ1N7a",
									layoutId: "VrtVZ1N7a",
									n8EcG8J9f: n8EcG8J9f1vy6ets,
									Sd0hNO3_y:
										"Roku charges a 1% trading fee on every buy and sell transaction. If you sign up using a referral link, you receive a 10% discount, reducing fees to 0.9%.",
									style: {
										width: "100%",
									},
									variant: "oQXrtGzL4",
									width: "100%",
									yZFelfvb7: "What are the trading fees on Roku?",
									...addPropertyOverrides2(
										{
											hSCJMr1Bi: {
												n8EcG8J9f: n8EcG8J9f1xmfrwg,
												variant: "guqzWnpoP",
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</SmartComponentScopedContainerWithFX>
						</ComponentViewportProvider2>
						<ComponentViewportProvider2
							height={112}
							width={componentViewport?.width || "100vw"}
							y={
								(componentViewport?.y || 0) +
								0 +
								(((componentViewport?.height || 656) - 0 - 656) / 2 + 448 + 96)
							}
							{...addPropertyOverrides2(
								{
									H01wOCsaP: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 736) - 0 - 656) / 2 +
												448 +
												96),
									},
									hSCJMr1Bi: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 200) - 0 - 656) / 2 +
												448 +
												96),
									},
									oBFKzsOBD: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 200) - 0 - 656) / 2 +
												448 +
												96),
									},
									OwG1Xm5fX: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 200) - 0 - 656) / 2 +
												448 +
												96),
									},
									YULiI2aDA: {
										y:
											(componentViewport?.y || 0) +
											0 +
											(((componentViewport?.height || 736) - 0 - 656) / 2 +
												448 +
												96),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<SmartComponentScopedContainerWithFX
								__framer__animate={{
									transition: transition2,
								}}
								__framer__animateOnce={true}
								__framer__enter={animation}
								__framer__styleAppearEffectEnabled={true}
								__framer__threshold={0.5}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								className={"framer-cqu9vu-container"}
								layoutDependency={layoutDependency}
								layoutId={"oXtPrHkrG-container"}
								nodeId={"oXtPrHkrG"}
								rendersWithMotion={true}
								scopeId={"qgfSEJic5"}
							>
								{_jsx2(stdin_default2, {
									height: "100%",
									id: "oXtPrHkrG",
									layoutId: "oXtPrHkrG",
									n8EcG8J9f: n8EcG8J9f1tdlyiz,
									Sd0hNO3_y:
										"If you need assistance, you can join our Telegram Support Group for realtime help, visit the Roku GitBook for step-by-step guides and FAQs, or follow our community channels to stay updated with announcements, tutorials, and tips.",
									style: {
										width: "100%",
									},
									variant: "oQXrtGzL4",
									width: "100%",
									yZFelfvb7: "Where can I get help if I run into issues?",
									...addPropertyOverrides2(
										{
											OwG1Xm5fX: {
												n8EcG8J9f: n8EcG8J9f1xmfrwg,
												variant: "guqzWnpoP",
											},
										},
										baseVariant,
										gestureVariant,
									),
								})}
							</SmartComponentScopedContainerWithFX>
						</ComponentViewportProvider2>
					</motion2.div>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-XxuLB.framer-1lsxg1z, .framer-XxuLB .framer-1lsxg1z { display: block; }",
	".framer-XxuLB.framer-1lrepgp { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1262px; }",
	".framer-XxuLB .framer-wzfnku-container, .framer-XxuLB .framer-1kc5fdc-container, .framer-XxuLB .framer-wtqtp2-container, .framer-XxuLB .framer-imy7yl-container, .framer-XxuLB .framer-cqu9vu-container { flex: none; height: auto; position: relative; width: 100%; }",
];
var FramerqgfSEJic5 = withCSS2(Component2, css4, "framer-XxuLB");
var stdin_default3 = FramerqgfSEJic5;
FramerqgfSEJic5.displayName = "FAQ/List";
FramerqgfSEJic5.defaultProps = {
	height: 656,
	width: 1262,
};
addPropertyControls2(FramerqgfSEJic5, {
	variant: {
		options: [
			"g92tKNYmW",
			"H01wOCsaP",
			"YULiI2aDA",
			"oBFKzsOBD",
			"hSCJMr1Bi",
			"OwG1Xm5fX",
		],
		optionTitles: [
			"Variant 1",
			"Variant 2",
			"Variant 3",
			"Variant 4",
			"Variant 5",
			"Variant 6",
		],
		title: "Variant",
		type: ControlType2.Enum,
	},
});
addFonts2(
	FramerqgfSEJic5,
	[
		{
			explicitInter: true,
			fonts: [],
		},
		...FAQItemFonts,
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:faq/list
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [
	{
		id: "bvzy1WeYw",
		name: "English",
		slug: "en",
		code: "en",
	},
];
var defaultResponsiveVariants = {
	base: "g92tKNYmW",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"f7de02364badfaa19730b887fe40769babb999f1ad18406989d28f58b996eb79"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ListFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"f7de02364badfaa19730b887fe40769babb999f1ad18406989d28f58b996eb79"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var list_default = ComponentWithRoot;
export { list_default as default };
