// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project f7de02364badfaa1 "Roku_ClientHandoff (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * 'en'
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Variant 1' | 'Variant 2' // Variant
}} Props

 */
import { routes } from "./chunks/chunk-VAWW4KIH.js";

// virtual:dots-2
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/wpvJU8GNuSesqS7cwh96/4gJjMY1z1dATik4w5d6q/SapbAdf_9.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useOnVariantChange,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["baX6izWUs", "lZm5s62Vl"];
var serializationHash = "framer-iH43V";
var variantClassNames = {
	baX6izWUs: "framer-v-t2ev8u",
	lZm5s62Vl: "framer-v-zthh9o",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	delay: 0,
	duration: 0.4,
	ease: [0.12, 0.23, 0.5, 1],
	type: "tween",
};
var transition2 = {
	delay: 0,
	duration: 0.4,
	ease: [0.5, 0, 0.88, 0.77],
	type: "tween",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Variant 1": "baX6izWUs",
	"Variant 2": "lZm5s62Vl",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "baX6izWUs",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "baX6izWUs",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onAppear1ihwd1s = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("lZm5s62Vl", true), 1e3);
	});
	const onAppear1xcofu2 = activeVariantCallback(async (...args) => {
		await delay(() => setVariant("baX6izWUs", true), 1e3);
	});
	const onTapb6hp1l = activeVariantCallback(async (...args) => {
		setVariant("lZm5s62Vl");
	});
	useOnVariantChange(baseVariant, {
		default: onAppear1ihwd1s,
		lZm5s62Vl: onAppear1xcofu2,
	});
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition
					value={transition1}
					{...addPropertyOverrides(
						{
							lZm5s62Vl: {
								value: transition2,
							},
						},
						baseVariant,
						gestureVariant,
					)}
				>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-t2ev8u",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						data-highlight={true}
						layoutDependency={layoutDependency}
						layoutId={"baX6izWUs"}
						ref={refBinding}
						style={{
							borderBottomLeftRadius: 100,
							borderBottomRightRadius: 100,
							borderTopLeftRadius: 100,
							borderTopRightRadius: 100,
							boxShadow: "0px 0px 4px 4px rgba(251, 158, 60, 0.2)",
							...style,
						}}
						variants={{
							lZm5s62Vl: {
								boxShadow: "0px 0px 0px 0px rgba(251, 158, 60, 0.2)",
							},
						}}
						{...addPropertyOverrides(
							{
								lZm5s62Vl: {
									"data-framer-name": "Variant 2",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1q79gwq"}
							data-border={true}
							data-highlight={true}
							layoutDependency={layoutDependency}
							layoutId={"ZXoxe31Td"}
							onTap={onTapb6hp1l}
							style={{
								"--border-bottom-width": "1px",
								"--border-color": "rgba(253, 165, 116, 0.3)",
								"--border-left-width": "1px",
								"--border-right-width": "1px",
								"--border-style": "solid",
								"--border-top-width": "1px",
								backgroundColor:
									"var(--token-9a96d3fa-fe16-4210-b1eb-731a6b45d9ca, rgb(250, 106, 46))",
								borderBottomLeftRadius: 100,
								borderBottomRightRadius: 100,
								borderTopLeftRadius: 100,
								borderTopRightRadius: 100,
							}}
						/>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-iH43V.framer-pcf01b, .framer-iH43V .framer-pcf01b { display: block; }",
	".framer-iH43V.framer-t2ev8u { height: 10px; overflow: visible; position: relative; width: 120px; }",
	".framer-iH43V .framer-1q79gwq { bottom: 0px; cursor: pointer; flex: none; left: 0px; overflow: visible; position: absolute; right: 0px; top: 0px; }",
	".framer-iH43V.framer-v-zthh9o.framer-t2ev8u { aspect-ratio: 1 / 1; height: var(--framer-aspect-ratio-supported, 120px); }",
	'.framer-iH43V[data-border="true"]::after, .framer-iH43V [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerSapbAdf_9 = withCSS(Component, css, "framer-iH43V");
var stdin_default = FramerSapbAdf_9;
FramerSapbAdf_9.displayName = "Dots 2";
FramerSapbAdf_9.defaultProps = {
	height: 120,
	width: 120,
};
addPropertyControls(FramerSapbAdf_9, {
	variant: {
		options: ["baX6izWUs", "lZm5s62Vl"],
		optionTitles: ["Variant 1", "Variant 2"],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramerSapbAdf_9,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:dots-2
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [
	{
		id: "bvzy1WeYw",
		name: "English",
		slug: "en",
		code: "en",
	},
];
var defaultResponsiveVariants = {
	base: "baX6izWUs",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"f7de02364badfaa19730b887fe40769babb999f1ad18406989d28f58b996eb79"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders Dots2FramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"f7de02364badfaa19730b887fe40769babb999f1ad18406989d28f58b996eb79"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var dots_2_default = ComponentWithRoot;
export { dots_2_default as default };
