// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project f7de02364badfaa1 "Roku_ClientHandoff (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * 'en'
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'White - 1 line' | 'White - 2 line' | 'Variant 3' | 'Variant 4' // Variant
 * title?: string // Title
 * description?: string // Description
 * icon?: undefined // Icon
 * bGColor?: string // BG Color
 * fill2?: string // Fill2
}} Props

 */
import { stdin_default } from "./chunks/chunk-FNV6YSDW.js";
import { className, css, fonts } from "./chunks/chunk-FNBO5TQO.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-UAGVO6ZV.js";
import { routes } from "./chunks/chunk-VAWW4KIH.js";

// virtual:features-1
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/6ar4DK33sS7sUt1wq4TA/gtzU4SjypFkebca2SCtV/QELqnrt7A.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	Instance,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
	withOptimizedAppearEffect,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var RichTextWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(
	withFX(RichText),
);
var cycleOrder = ["JzGeGPVkI", "QGhIjERZw", "JpRZDlD0K", "noOc7cnS5"];
var serializationHash = "framer-SmjSY";
var variantClassNames = {
	JpRZDlD0K: "framer-v-lnn5db",
	JzGeGPVkI: "framer-v-1dg8jla",
	noOc7cnS5: "framer-v-1vyefjh",
	QGhIjERZw: "framer-v-13x3rw8",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transition2 = {
	delay: 0.5,
	duration: 0.9,
	ease: [0.22, 0.85, 0.56, 1],
	type: "tween",
};
var animation = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 0,
	y: 0,
};
var animation1 = {
	opacity: 1e-3,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 30,
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Variant 3": "JpRZDlD0K",
	"Variant 4": "noOc7cnS5",
	"White - 1 line": "JzGeGPVkI",
	"White - 2 line": "QGhIjERZw",
};
var getProps = ({
	bGColor,
	description,
	fill2,
	height,
	icon,
	id,
	title,
	width,
	...props
}) => {
	return {
		...props,
		cqm6RCLuj: description ?? props.cqm6RCLuj ?? "Description",
		eoEopiHnI:
			bGColor ??
			props.eoEopiHnI ??
			"var(--token-a096d81a-91db-425a-b2a9-ca48ac283707, rgb(255, 255, 255))",
		NjLCz_pMC: title ?? props.NjLCz_pMC ?? "Title",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "JzGeGPVkI",
		w8JKGNYmM:
			fill2 ??
			props.w8JKGNYmM ??
			"var(--token-e151dd1b-3011-4af4-b6a1-16337cf14949, rgb(0, 0, 0))",
		yeqyA7Ci3: icon ?? props.yeqyA7Ci3 ?? stdin_default,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		NjLCz_pMC,
		cqm6RCLuj,
		yeqyA7Ci3,
		eoEopiHnI,
		w8JKGNYmM,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "JzGeGPVkI",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1dg8jla",
							className3,
							classNames,
						)}
						data-framer-name={"White - 1 line"}
						layoutDependency={layoutDependency}
						layoutId={"JzGeGPVkI"}
						ref={refBinding}
						style={{
							backgroundColor: eoEopiHnI,
							borderBottomLeftRadius: 30,
							borderBottomRightRadius: 30,
							borderTopLeftRadius: 30,
							borderTopRightRadius: 30,
							...style,
						}}
						{...addPropertyOverrides(
							{
								JpRZDlD0K: {
									"data-framer-name": "Variant 3",
								},
								noOc7cnS5: {
									"data-framer-name": "Variant 4",
								},
								QGhIjERZw: {
									"data-framer-name": "White - 2 line",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1js00aq"}
							layoutDependency={layoutDependency}
							layoutId={"EyIqGSDox"}
							style={{
								backgroundColor: w8JKGNYmM,
								borderBottomLeftRadius: 16,
								borderBottomRightRadius: 16,
								borderTopLeftRadius: 16,
								borderTopRightRadius: 16,
							}}
							variants={{
								JpRZDlD0K: {
									borderBottomLeftRadius: 4,
									borderBottomRightRadius: 4,
									borderTopLeftRadius: 4,
									borderTopRightRadius: 4,
								},
								noOc7cnS5: {
									borderBottomLeftRadius: 4,
									borderBottomRightRadius: 4,
									borderTopLeftRadius: 4,
									borderTopRightRadius: 4,
								},
							}}
						>
							<Instance
								animated={true}
								className={"framer-6uj2t5"}
								Component={yeqyA7Ci3}
								layoutDependency={layoutDependency}
								layoutId={"PckBPRJhy"}
								style={{
									"--9c46k4":
										"var(--token-a096d81a-91db-425a-b2a9-ca48ac283707, rgb(255, 255, 255))",
								}}
							/>
						</motion.div>
						<motion.div
							className={"framer-197d0h6"}
							layoutDependency={layoutDependency}
							layoutId={"AaeWSPi8e"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-jgtz4x"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"oIYOrX_a3"}
								text={NjLCz_pMC}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-4nmvol"}
										data-styles-preset={"SbGP7ycJT"}
									>
										{"Title"}
									</motion.p>
								</React.Fragment>
							</RichText>
							<RichTextWithFXWithOptimizedAppearEffect
								__fromCanvasComponent={true}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								animate={animation}
								className={"framer-t85qb"}
								data-framer-appear-id={"t85qb"}
								fonts={["Inter"]}
								initial={animation1}
								layoutDependency={layoutDependency}
								layoutId={"t82wqFuvO"}
								optimized={true}
								style={{
									"--extracted-r6o4lv":
										"var(--token-0d09ba75-26a4-4e48-a43d-731b581e642d, rgb(41, 48, 86))",
								}}
								text={cqm6RCLuj}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-6qj0qo"}
										data-styles-preset={"PylgTZkRS"}
										style={{
											"--framer-text-alignment": "left",
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-0d09ba75-26a4-4e48-a43d-731b581e642d, rgb(41, 48, 86)))",
										}}
									>
										{"Description"}
									</motion.p>
								</React.Fragment>
							</RichTextWithFXWithOptimizedAppearEffect>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-SmjSY.framer-upxzcv, .framer-SmjSY .framer-upxzcv { display: block; }",
	".framer-SmjSY.framer-1dg8jla { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; height: min-content; justify-content: space-between; min-height: 329px; overflow: var(--overflow-clip-fallback, clip); padding: 32px; position: relative; width: 389px; will-change: var(--framer-will-change-override, transform); }",
	".framer-SmjSY .framer-1js00aq { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: 72px; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 72px; will-change: var(--framer-will-change-override, transform); }",
	".framer-SmjSY .framer-6uj2t5 { flex: none; height: var(--framer-aspect-ratio-supported, 43px); position: relative; width: 43px; }",
	".framer-SmjSY .framer-197d0h6 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 100%; }",
	".framer-SmjSY .framer-jgtz4x { flex: none; height: 34px; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-SmjSY .framer-t85qb { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-SmjSY.framer-v-13x3rw8 .framer-jgtz4x { height: 68px; }",
	".framer-SmjSY.framer-v-lnn5db.framer-1dg8jla { gap: 28px; justify-content: flex-start; min-height: 315px; width: 258px; }",
	".framer-SmjSY.framer-v-lnn5db .framer-1js00aq, .framer-SmjSY.framer-v-1vyefjh .framer-1js00aq { height: 32px; width: 32px; }",
	".framer-SmjSY.framer-v-lnn5db .framer-6uj2t5 { height: var(--framer-aspect-ratio-supported, 24px); width: 24px; }",
	".framer-SmjSY.framer-v-lnn5db .framer-jgtz4x, .framer-SmjSY.framer-v-1vyefjh .framer-jgtz4x { height: auto; }",
	".framer-SmjSY.framer-v-1vyefjh.framer-1dg8jla { gap: 28px; justify-content: flex-start; min-height: unset; width: 258px; }",
	".framer-SmjSY.framer-v-1vyefjh .framer-6uj2t5 { width: 24px; }",
	...css2,
	...css,
];
var FramerQELqnrt7A = withCSS(Component, css3, "framer-SmjSY");
var stdin_default2 = FramerQELqnrt7A;
FramerQELqnrt7A.displayName = "Features 1";
FramerQELqnrt7A.defaultProps = {
	height: 329,
	width: 389,
};
addPropertyControls(FramerQELqnrt7A, {
	variant: {
		options: ["JzGeGPVkI", "QGhIjERZw", "JpRZDlD0K", "noOc7cnS5"],
		optionTitles: [
			"White - 1 line",
			"White - 2 line",
			"Variant 3",
			"Variant 4",
		],
		title: "Variant",
		type: ControlType.Enum,
	},
	NjLCz_pMC: {
		defaultValue: "Title",
		displayTextArea: true,
		title: "Title",
		type: ControlType.String,
	},
	cqm6RCLuj: {
		defaultValue: "Description",
		displayTextArea: true,
		title: "Description",
		type: ControlType.String,
	},
	yeqyA7Ci3: {
		defaultValue: {
			identifier: "local-module:vector/Ot__tv4MW:default",
			moduleId: "lGznTf5WyCl5NAR6g58O",
		},
		setModuleId: "dHG9nZXOguxaGzINUDnb",
		title: "Icon",
		type: ControlType.VectorSetItem,
	},
	eoEopiHnI: {
		defaultValue:
			"var(--token-a096d81a-91db-425a-b2a9-ca48ac283707, rgb(255, 255, 255))",
		title: "BG Color",
		type: ControlType.Color,
	},
	w8JKGNYmM: {
		defaultValue:
			"var(--token-e151dd1b-3011-4af4-b6a1-16337cf14949, rgb(0, 0, 0))",
		title: "Fill2",
		type: ControlType.Color,
	},
});
addFonts(
	FramerQELqnrt7A,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:features-1
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [
	{
		id: "bvzy1WeYw",
		name: "English",
		slug: "en",
		code: "en",
	},
];
var defaultResponsiveVariants = {
	base: "noOc7cnS5",
	md: "JpRZDlD0K",
	xl: "JzGeGPVkI",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"f7de02364badfaa19730b887fe40769babb999f1ad18406989d28f58b996eb79"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders Features1FramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"f7de02364badfaa19730b887fe40769babb999f1ad18406989d28f58b996eb79"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var features_1_default = ComponentWithRoot;
export { features_1_default as default };
