// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project f7de02364badfaa1 "Roku_ClientHandoff (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * 'en'
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Mobile' | 'Variant 3' // Variant
 * displayName?: string // Display Name
 * username?: string // Username
 * text?: string // Text
 * image?: {src: string, srcSet?: string, alt?: string} // Image
 * showVerified?: boolean // show verified
 * bGColor?: string // BG Color
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-UMPRUBXN.js";
import { routes } from "./chunks/chunk-VAWW4KIH.js";

// virtual:item
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/um8SHunJHKMqooHMyV1L/y9LldCoWqQwmAMO5dwgO/QocAYOmzm.js
import { jsx as _jsx2, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls2,
	ControlType as ControlType2,
	cx as cx2,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS as withCSS2,
} from "unframer";
import { LayoutGroup, motion as motion2, MotionConfigContext } from "unframer";
import * as React2 from "react";
import { useRef } from "react";

// /:https://framerusercontent.com/modules/1amVoOheAxNIUNUpwCEL/fFjeQM4ryIHKYocYyUfU/AGjkzJAIF.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addPropertyControls,
	ControlType,
	cx,
	motion,
	withCSS,
} from "unframer";
import * as React from "react";
import { forwardRef as forwardRef2 } from "react";
var mask = `url('data:image/svg+xml,<svg display="block" role="presentation" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg"><path d="M 7.213 8.196 L 6.126 7.128 C 5.989 6.991 5.817 6.922 5.612 6.922 C 5.406 6.922 5.228 6.997 5.077 7.147 C 4.94 7.284 4.871 7.459 4.871 7.671 C 4.871 7.884 4.94 8.058 5.077 8.196 L 6.689 9.807 C 6.838 9.957 7.013 10.032 7.213 10.032 C 7.413 10.032 7.588 9.957 7.738 9.807 L 10.923 6.622 C 11.073 6.472 11.144 6.297 11.138 6.097 C 11.131 5.898 11.06 5.723 10.923 5.573 C 10.773 5.423 10.595 5.345 10.389 5.339 C 10.183 5.333 10.005 5.405 9.855 5.554 Z M 5.115 14.978 L 4.028 13.142 L 1.967 12.692 C 1.78 12.655 1.63 12.558 1.518 12.402 C 1.405 12.246 1.361 12.075 1.386 11.887 L 1.593 9.77 L 0.187 8.158 C 0.062 8.021 0 7.859 0 7.671 C 0 7.484 0.062 7.322 0.187 7.184 L 1.593 5.573 L 1.386 3.456 C 1.361 3.268 1.405 3.097 1.518 2.94 C 1.63 2.784 1.78 2.687 1.967 2.65 L 4.028 2.201 L 5.115 0.364 C 5.215 0.202 5.352 0.093 5.527 0.036 C 5.702 -0.02 5.877 -0.011 6.052 0.065 L 8 0.889 L 9.948 0.065 C 10.123 -0.01 10.298 -0.02 10.473 0.036 C 10.648 0.092 10.785 0.202 10.885 0.364 L 11.972 2.201 L 14.033 2.65 C 14.22 2.688 14.37 2.785 14.482 2.941 C 14.595 3.097 14.639 3.269 14.614 3.456 L 14.407 5.573 L 15.813 7.184 C 15.938 7.322 16 7.484 16 7.671 C 16 7.859 15.938 8.021 15.813 8.158 L 14.407 9.77 L 14.614 11.887 C 14.639 12.074 14.595 12.246 14.482 12.402 C 14.37 12.559 14.22 12.655 14.033 12.692 L 11.972 13.142 L 10.885 14.978 C 10.785 15.14 10.648 15.25 10.473 15.306 C 10.298 15.363 10.123 15.353 9.948 15.278 L 8 14.453 L 6.052 15.278 C 5.877 15.353 5.702 15.362 5.527 15.306 C 5.352 15.25 5.215 15.141 5.115 14.978" fill="var(--1prn4g3, var(--token-67ca5fa7-a56e-420c-a780-e11145832d94, rgb(164, 167, 174)))" height="15.34254683840707px" id="I2OVHcF8I" transform="translate(0 0.5)" width="16px"/></svg>') alpha no-repeat center / auto var(--framer-icon-mask-mode, add), var(--framer-icon-mask, none)`;
var SVG = /* @__PURE__ */ forwardRef2((props, ref) => {
	const { animated, layoutId, children, ...rest } = props;
	return animated ? (
		<motion.div {...rest} layoutId={layoutId} ref={ref} />
	) : (
		<div {...rest} ref={ref} />
	);
});
var getProps = ({ color, height, id, width, ...props }) => {
	return {
		...props,
		BiGjbtiAo:
			color ??
			props.BiGjbtiAo ??
			"var(--token-67ca5fa7-a56e-420c-a780-e11145832d94, rgb(164, 167, 174))",
	};
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const {
		style,
		className: className2,
		layoutId,
		variant,
		BiGjbtiAo,
		...restProps
	} = getProps(props);
	return (
		<SVG
			{...restProps}
			className={cx("framer-YapMl", className2)}
			layoutId={layoutId}
			ref={ref}
			style={{
				"--1prn4g3": BiGjbtiAo,
				...style,
			}}
		/>
	);
});
var css2 = [
	`.framer-YapMl { -webkit-mask: ${mask}; aspect-ratio: 1; background-color: var(--1prn4g3); mask: ${mask}; width: 16px; }`,
];
var Icon = withCSS(Component, css2, "framer-YapMl");
Icon.displayName = "Vector";
var stdin_default = Icon;
addPropertyControls(Icon, {
	BiGjbtiAo: {
		defaultValue:
			'var(--token-67ca5fa7-a56e-420c-a780-e11145832d94, rgb(164, 167, 174)) /* {"name":"N400"} */',
		hidden: false,
		title: "Color",
		type: ControlType.Color,
	},
});

// /:https://framerusercontent.com/modules/um8SHunJHKMqooHMyV1L/y9LldCoWqQwmAMO5dwgO/QocAYOmzm.js
var VectorFonts = getFonts(stdin_default);
var cycleOrder = ["nim05sm5G", "ZDlC9Xr51", "VTtZcD1cA"];
var serializationHash = "framer-gKGAU";
var variantClassNames = {
	nim05sm5G: "framer-v-1q6zety",
	VTtZcD1cA: "framer-v-1su1k65",
	ZDlC9Xr51: "framer-v-sxcy4o",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion2.create(React2.Fragment);
var humanReadableVariantMap = {
	"Variant 3": "VTtZcD1cA",
	Desktop: "nim05sm5G",
	Mobile: "ZDlC9Xr51",
};
var getProps2 = ({
	bGColor,
	displayName,
	height,
	id,
	image,
	showVerified,
	text,
	username,
	width,
	...props
}) => {
	return {
		...props,
		biE3Cgt1b: username ?? props.biE3Cgt1b ?? "@",
		CKTUn_unk: image ?? props.CKTUn_unk,
		Iam2qwGKA: showVerified ?? props.Iam2qwGKA ?? true,
		Jd6if891o: text ?? props.Jd6if891o ?? "Text",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "nim05sm5G",
		whf_RTONr:
			bGColor ??
			props.whf_RTONr ??
			"var(--token-6bb35d22-2ec1-489a-87da-8b723b59a265, rgb(248, 249, 252))",
		whYrW7ajw: displayName ?? props.whYrW7ajw ?? "Display Name",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		whYrW7ajw,
		biE3Cgt1b,
		Jd6if891o,
		CKTUn_unk,
		Iam2qwGKA,
		whf_RTONr,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "nim05sm5G",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx2(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion2.div
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-1q6zety",
							className2,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"nim05sm5G"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-023c0b02-d6e9-49e1-83e1-ac1f4183d641, rgb(227, 232, 239))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							backdropFilter: "blur(0px)",
							backgroundColor: whf_RTONr,
							borderBottomLeftRadius: 16,
							borderBottomRightRadius: 16,
							borderTopLeftRadius: 16,
							borderTopRightRadius: 16,
							WebkitBackdropFilter: "blur(0px)",
							...style,
						}}
						variants={{
							ZDlC9Xr51: {
								backgroundColor:
									"var(--token-6bb35d22-2ec1-489a-87da-8b723b59a265, rgb(248, 249, 252))",
							},
						}}
						{...addPropertyOverrides(
							{
								VTtZcD1cA: {
									"data-framer-name": "Variant 3",
								},
								ZDlC9Xr51: {
									"data-framer-name": "Mobile",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion2.div
							className={"framer-1d5ia32"}
							data-framer-name={"Container"}
							layoutDependency={layoutDependency}
							layoutId={"XwrS1GYOp"}
						>
							<motion2.div
								className={"framer-1k4fldh"}
								data-framer-name={"Container"}
								layoutDependency={layoutDependency}
								layoutId={"ZDimbwFvk"}
							>
								<motion2.div
									className={"framer-1fjzilc"}
									layoutDependency={layoutDependency}
									layoutId={"ZATJjLx2r"}
								>
									<motion2.div
										className={"framer-12wtyn1"}
										layoutDependency={layoutDependency}
										layoutId={"wzMSa4G6Y"}
									>
										<RichText
											__fromCanvasComponent={true}
											className={"framer-1i6bogb"}
											data-framer-name={"Name"}
											fonts={["Inter"]}
											layoutDependency={layoutDependency}
											layoutId={"wcWJvAt9l"}
											style={{
												"--extracted-r6o4lv":
													"var(--token-2a5ef645-a3a4-4c5f-ba45-e629298b1709, rgb(1, 0, 5))",
												"--framer-paragraph-spacing": "0px",
											}}
											text={whYrW7ajw}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React2.Fragment>
												<motion2.p
													className={"framer-styles-preset-iwvh3s"}
													data-styles-preset={"l6xYtvRSA"}
													style={{
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-2a5ef645-a3a4-4c5f-ba45-e629298b1709, rgb(1, 0, 5)))",
													}}
												>
													{"Display Name"}
												</motion2.p>
											</React2.Fragment>
										</RichText>
										{Iam2qwGKA &&
											_jsx2(stdin_default, {
												animated: true,
												className: "framer-wns5go",
												layoutDependency,
												layoutId: "z7Y8gKeLX",
												style: {
													"--1prn4g3": "rgb(29, 155, 240)",
												},
											})}
									</motion2.div>
									<RichText
										__fromCanvasComponent={true}
										className={"framer-shwxhh"}
										data-framer-name={"Name"}
										fonts={["Inter"]}
										layoutDependency={layoutDependency}
										layoutId={"z9hDPtOkt"}
										style={{
											"--extracted-r6o4lv":
												"var(--token-7e83bec4-73bd-4dcd-b0c4-908ed6b9fc9e, rgb(124, 124, 124))",
											"--framer-paragraph-spacing": "0px",
										}}
										text={biE3Cgt1b}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React2.Fragment>
											<motion2.p
												className={"framer-styles-preset-iwvh3s"}
												data-styles-preset={"l6xYtvRSA"}
												style={{
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-7e83bec4-73bd-4dcd-b0c4-908ed6b9fc9e, rgb(124, 124, 124)))",
												}}
											>
												{"Name"}
											</motion2.p>
										</React2.Fragment>
									</RichText>
								</motion2.div>
							</motion2.div>
						</motion2.div>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-1wh5zk6"}
							data-framer-name={"Quote"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"cBcrv2mir"}
							style={{
								"--extracted-r6o4lv":
									"var(--token-e151dd1b-3011-4af4-b6a1-16337cf14949, rgb(0, 0, 0))",
								"--framer-paragraph-spacing": "0px",
							}}
							text={Jd6if891o}
							verticalAlignment={"top"}
							withExternalLayout={true}
						>
							<React2.Fragment>
								<motion2.p
									className={"framer-styles-preset-iwvh3s"}
									data-styles-preset={"l6xYtvRSA"}
									style={{
										"--framer-text-color":
											"var(--extracted-r6o4lv, var(--token-e151dd1b-3011-4af4-b6a1-16337cf14949, rgb(0, 0, 0)))",
									}}
								>
									{"Quote"}
								</motion2.p>
							</React2.Fragment>
						</RichText>
						<Image
							background={{
								alt: "",
								fit: "fill",
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) + 16 + 214,
								),
								sizes: `calc(${componentViewport?.width || "100vw"} - 40px)`,
								...toResponsiveImage(CKTUn_unk),
							}}
							className={"framer-q3tr1n"}
							layoutDependency={layoutDependency}
							layoutId={"KE3eR_Qs5"}
							style={{
								borderBottomLeftRadius: 8,
								borderBottomRightRadius: 8,
								borderTopLeftRadius: 8,
								borderTopRightRadius: 8,
							}}
							{...addPropertyOverrides(
								{
									ZDlC9Xr51: {
										background: {
											alt: "",
											fit: "fill",
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) + 24 + 214,
											),
											sizes: `calc(${componentViewport?.width || "100vw"} - 48px)`,
											...toResponsiveImage(CKTUn_unk),
										},
									},
								},
								baseVariant,
								gestureVariant,
							)}
						/>
					</motion2.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-gKGAU.framer-t3k69d, .framer-gKGAU .framer-t3k69d { display: block; }",
	".framer-gKGAU.framer-1q6zety { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: visible; padding: 16px 20px 20px 20px; position: relative; width: 400px; }",
	".framer-gKGAU .framer-1d5ia32 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-gKGAU .framer-1k4fldh { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 24px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-gKGAU .framer-1fjzilc { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-gKGAU .framer-12wtyn1 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: flex-start; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-gKGAU .framer-1i6bogb { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-gKGAU .framer-wns5go { flex: none; height: var(--framer-aspect-ratio-supported, 14px); position: relative; width: 14px; }",
	".framer-gKGAU .framer-shwxhh, .framer-gKGAU .framer-1wh5zk6 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-gKGAU .framer-q3tr1n { aspect-ratio: 1.7796610169491525 / 1; flex: none; height: var(--framer-aspect-ratio-supported, 202px); overflow: var(--overflow-clip-fallback, clip); position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }",
	".framer-gKGAU.framer-v-sxcy4o.framer-1q6zety { padding: 24px; width: 390px; }",
	".framer-gKGAU.framer-v-sxcy4o .framer-q3tr1n { height: var(--framer-aspect-ratio-supported, 192px); }",
	".framer-gKGAU.framer-v-1su1k65 .framer-1wh5zk6 { min-height: 54px; }",
	".framer-gKGAU.framer-v-1su1k65 .framer-q3tr1n { height: var(--framer-aspect-ratio-supported, 112px); }",
	...css,
	'.framer-gKGAU[data-border="true"]::after, .framer-gKGAU [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerQocAYOmzm = withCSS2(Component2, css3, "framer-gKGAU");
var stdin_default2 = FramerQocAYOmzm;
FramerQocAYOmzm.displayName = "Item";
FramerQocAYOmzm.defaultProps = {
	height: 308,
	width: 400,
};
addPropertyControls2(FramerQocAYOmzm, {
	variant: {
		options: ["nim05sm5G", "ZDlC9Xr51", "VTtZcD1cA"],
		optionTitles: ["Desktop", "Mobile", "Variant 3"],
		title: "Variant",
		type: ControlType2.Enum,
	},
	whYrW7ajw: {
		defaultValue: "Display Name",
		description: "Name",
		displayTextArea: false,
		title: "Display Name",
		type: ControlType2.String,
	},
	biE3Cgt1b: {
		defaultValue: "@",
		displayTextArea: false,
		title: "Username",
		type: ControlType2.String,
	},
	Jd6if891o: {
		defaultValue: "Text",
		displayTextArea: true,
		title: "Text",
		type: ControlType2.String,
	},
	CKTUn_unk: {
		title: "Image",
		type: ControlType2.ResponsiveImage,
	},
	Iam2qwGKA: {
		defaultValue: true,
		title: "show verified",
		type: ControlType2.Boolean,
	},
	whf_RTONr: {
		defaultValue:
			"var(--token-6bb35d22-2ec1-489a-87da-8b723b59a265, rgb(248, 249, 252))",
		title: "BG Color",
		type: ControlType2.Color,
	},
});
addFonts(
	FramerQocAYOmzm,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...VectorFonts,
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:item
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [
	{
		id: "bvzy1WeYw",
		name: "English",
		slug: "en",
		code: "en",
	},
];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"f7de02364badfaa19730b887fe40769babb999f1ad18406989d28f58b996eb79"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders ItemFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"f7de02364badfaa19730b887fe40769babb999f1ad18406989d28f58b996eb79"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var item_default = ComponentWithRoot;
export { item_default as default };
