// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project f7de02364badfaa1 "Roku_ClientHandoff (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * 'en'
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'sm_white_brand' | 'sm_white_white' | 'md_grey_brand' | 'md_white' | 'sm_grey' | 'Variant 6' // Variant
 * link?: string // Link
 * text?: string // Text
 * showLeadingIcon?: boolean // Show Leading Icon
 * leadingIcon?: undefined // Leading Icon
 * showTrailingIcon?: boolean // Show Trailing Icon
 * trailingIcon?: undefined // Trailing Icon
 * click?: Function // Click
}} Props

 */
import { stdin_default, stdin_default2 } from "./chunks/chunk-JYM3MGXX.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-FNBO5TQO.js";
import { className, css, fonts } from "./chunks/chunk-UMPRUBXN.js";
import { routes } from "./chunks/chunk-VAWW4KIH.js";

// virtual:nav-link-without-stack
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/n57YeUS6nnbt02BcAgRt/eOCLmtJNw1S1rJSPuASw/U1GUUBfW3.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	Instance,
	Link,
	RichText,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var enabledGestures = {
	QOkbEaKc1: {
		hover: true,
	},
	rX2dRQW7L: {
		hover: true,
	},
	TBuOwI4Yw: {
		hover: true,
	},
	TECUXFAwv: {
		hover: true,
	},
	WllZCZIzo: {
		hover: true,
	},
	ZediBAWvQ: {
		hover: true,
	},
};
var cycleOrder = [
	"TBuOwI4Yw",
	"rX2dRQW7L",
	"QOkbEaKc1",
	"WllZCZIzo",
	"ZediBAWvQ",
	"TECUXFAwv",
];
var serializationHash = "framer-ngZZ6";
var variantClassNames = {
	QOkbEaKc1: "framer-v-1xhsjev",
	rX2dRQW7L: "framer-v-570cjb",
	TBuOwI4Yw: "framer-v-1ch3cf2",
	TECUXFAwv: "framer-v-ylwb8w",
	WllZCZIzo: "framer-v-1g212v0",
	ZediBAWvQ: "framer-v-1dra12n",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Variant 6": "TECUXFAwv",
	md_grey_brand: "QOkbEaKc1",
	md_white: "WllZCZIzo",
	sm_grey: "ZediBAWvQ",
	sm_white_brand: "TBuOwI4Yw",
	sm_white_white: "rX2dRQW7L",
};
var getProps = ({
	click,
	height,
	id,
	leadingIcon,
	link,
	showLeadingIcon,
	showTrailingIcon,
	text,
	trailingIcon,
	width,
	...props
}) => {
	return {
		...props,
		ae_saHjca: click ?? props.ae_saHjca,
		B6JoyuVBD: showLeadingIcon ?? props.B6JoyuVBD ?? true,
		huAKLjz4K: link ?? props.huAKLjz4K,
		szA1JNrqU: trailingIcon ?? props.szA1JNrqU ?? stdin_default,
		Uv1sGVFd3: leadingIcon ?? props.Uv1sGVFd3 ?? stdin_default2,
		UwCPZFy3L: text ?? props.UwCPZFy3L ?? "Text",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "TBuOwI4Yw",
		XRG0F6f0o: showTrailingIcon ?? props.XRG0F6f0o ?? true,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		huAKLjz4K,
		UwCPZFy3L,
		B6JoyuVBD,
		Uv1sGVFd3,
		XRG0F6f0o,
		szA1JNrqU,
		ae_saHjca,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "TBuOwI4Yw",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap1fqik1t = activeVariantCallback(async (...args) => {
		setGestureState({
			isPressed: false,
		});
		if (ae_saHjca) {
			const res = await ae_saHjca(...args);
			if (res === false) return false;
		}
	});
	const sharedStyleClassNames = [className, className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = (value) => {
		if (
			["QOkbEaKc1-hover", "WllZCZIzo-hover", "TECUXFAwv-hover"].includes(
				gestureVariant,
			)
		)
			return value;
		if (["QOkbEaKc1", "WllZCZIzo", "TECUXFAwv"].includes(baseVariant))
			return value;
		return false;
	};
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<Link
						href={huAKLjz4K}
						motionChild={true}
						nodeId={"TBuOwI4Yw"}
						openInNewTab={false}
						scopeId={"U1GUUBfW3"}
						smoothScroll={true}
					>
						<motion.a
							{...restProps}
							{...gestureHandlers}
							className={`${cx(scopingClassNames, "framer-1ch3cf2", className3, classNames)} framer-1b4ujsb`}
							data-framer-name={"sm_white_brand"}
							data-highlight={true}
							layoutDependency={layoutDependency}
							layoutId={"TBuOwI4Yw"}
							onTap={onTap1fqik1t}
							ref={refBinding}
							style={{
								...style,
							}}
							{...addPropertyOverrides(
								{
									"QOkbEaKc1-hover": {
										"data-framer-name": void 0,
									},
									"rX2dRQW7L-hover": {
										"data-framer-name": void 0,
									},
									"TBuOwI4Yw-hover": {
										"data-framer-name": void 0,
									},
									"TECUXFAwv-hover": {
										"data-framer-name": void 0,
									},
									"WllZCZIzo-hover": {
										"data-framer-name": void 0,
									},
									"ZediBAWvQ-hover": {
										"data-framer-name": void 0,
									},
									QOkbEaKc1: {
										"data-framer-name": "md_grey_brand",
									},
									rX2dRQW7L: {
										"data-framer-name": "sm_white_white",
									},
									TECUXFAwv: {
										"data-framer-name": "Variant 6",
									},
									WllZCZIzo: {
										"data-framer-name": "md_white",
									},
									ZediBAWvQ: {
										"data-framer-name": "sm_grey",
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							{B6JoyuVBD && (
								<Instance
									animated={true}
									className={"framer-1c1tepx"}
									Component={Uv1sGVFd3}
									layoutDependency={layoutDependency}
									layoutId={"ESrkqxyrR"}
									style={{
										"--1prn4g3":
											"var(--token-67ca5fa7-a56e-420c-a780-e11145832d94, rgb(164, 167, 174))",
									}}
									variants={{
										"WllZCZIzo-hover": {
											"--1prn4g3":
												"var(--token-a096d81a-91db-425a-b2a9-ca48ac283707, rgb(255, 255, 255))",
										},
										TECUXFAwv: {
											"--1prn4g3":
												"var(--token-e151dd1b-3011-4af4-b6a1-16337cf14949, rgb(0, 0, 0))",
										},
									}}
								/>
							)}
							<motion.div
								className={"framer-xq94vk"}
								layoutDependency={layoutDependency}
								layoutId={"C0iFerNF1"}
							>
								{isDisplayed(XRG0F6f0o) && (
									<Instance
										animated={true}
										className={"framer-cou9o9"}
										Component={szA1JNrqU}
										layoutDependency={layoutDependency}
										layoutId={"pSqqKFRhe"}
										style={{
											"--1prn4g3":
												"var(--token-67ca5fa7-a56e-420c-a780-e11145832d94, rgb(164, 167, 174))",
										}}
										variants={{
											"WllZCZIzo-hover": {
												"--1prn4g3":
													"var(--token-a096d81a-91db-425a-b2a9-ca48ac283707, rgb(255, 255, 255))",
											},
											TECUXFAwv: {
												"--1prn4g3":
													"var(--token-e151dd1b-3011-4af4-b6a1-16337cf14949, rgb(0, 0, 0))",
											},
										}}
									/>
								)}
								<RichText
									__fromCanvasComponent={true}
									className={"framer-1qd6em8"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"FsBrztJ91"}
									style={{
										"--extracted-r6o4lv": "rgba(255, 255, 255, 0.7)",
									}}
									text={UwCPZFy3L}
									variants={{
										"QOkbEaKc1-hover": {
											"--extracted-r6o4lv":
												"var(--token-0d09ba75-26a4-4e48-a43d-731b581e642d, rgb(70, 70, 70))",
										},
										"rX2dRQW7L-hover": {
											"--extracted-r6o4lv":
												"var(--token-a096d81a-91db-425a-b2a9-ca48ac283707, rgb(255, 255, 255))",
										},
										"TBuOwI4Yw-hover": {
											"--extracted-r6o4lv":
												"var(--token-10e900e6-2b0e-4f3a-9241-1d67cf11b555, rgb(255, 129, 10))",
										},
										"TECUXFAwv-hover": {
											"--extracted-r6o4lv":
												"var(--token-b0e52b43-0d8f-445a-bc4d-d196172acda5, rgb(36, 183, 253))",
										},
										"WllZCZIzo-hover": {
											"--extracted-r6o4lv":
												"var(--token-a096d81a-91db-425a-b2a9-ca48ac283707, rgb(255, 255, 255))",
										},
										"ZediBAWvQ-hover": {
											"--extracted-r6o4lv":
												"var(--token-2a5ef645-a3a4-4c5f-ba45-e629298b1709, rgb(41, 41, 41))",
										},
										QOkbEaKc1: {
											"--extracted-r6o4lv":
												"var(--token-4efc64a6-207c-4d82-a4fe-235a43565dac, rgb(61, 61, 61))",
										},
										TECUXFAwv: {
											"--extracted-r6o4lv":
												"var(--token-2a5ef645-a3a4-4c5f-ba45-e629298b1709, rgb(1, 0, 5))",
										},
										WllZCZIzo: {
											"--extracted-r6o4lv":
												"var(--token-67ca5fa7-a56e-420c-a780-e11145832d94, rgb(152, 152, 152))",
										},
										ZediBAWvQ: {
											"--extracted-r6o4lv":
												"var(--token-e27967ec-8d88-49ef-9be2-8e921a13da7d, rgb(82, 82, 82))",
										},
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
									{...addPropertyOverrides(
										{
											"QOkbEaKc1-hover": {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-6qj0qo"}
															data-styles-preset={"PylgTZkRS"}
															style={{
																"--framer-text-alignment": "left",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-0d09ba75-26a4-4e48-a43d-731b581e642d, rgb(70, 70, 70)))",
															}}
														>
															{"Text"}
														</motion.p>
													</React.Fragment>
												),
											},
											"rX2dRQW7L-hover": {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-iwvh3s"}
															data-styles-preset={"l6xYtvRSA"}
															style={{
																"--framer-text-alignment": "left",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-a096d81a-91db-425a-b2a9-ca48ac283707, rgb(255, 255, 255)))",
															}}
														>
															{
																"Jl. Halim Perdana Kusuma, Jurumudi Baru, Benda, Kota Tangerang"
															}
														</motion.p>
													</React.Fragment>
												),
											},
											"TBuOwI4Yw-hover": {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-iwvh3s"}
															data-styles-preset={"l6xYtvRSA"}
															style={{
																"--framer-text-alignment": "left",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-10e900e6-2b0e-4f3a-9241-1d67cf11b555, rgb(255, 129, 10)))",
															}}
														>
															{
																"Jl. Halim Perdana Kusuma, Jurumudi Baru, Benda, Kota Tangerang"
															}
														</motion.p>
													</React.Fragment>
												),
											},
											"TECUXFAwv-hover": {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-6qj0qo"}
															data-styles-preset={"PylgTZkRS"}
															style={{
																"--framer-text-alignment": "left",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-b0e52b43-0d8f-445a-bc4d-d196172acda5, rgb(36, 183, 253)))",
															}}
														>
															{"Text"}
														</motion.p>
													</React.Fragment>
												),
											},
											"WllZCZIzo-hover": {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-6qj0qo"}
															data-styles-preset={"PylgTZkRS"}
															style={{
																"--framer-text-alignment": "left",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-a096d81a-91db-425a-b2a9-ca48ac283707, rgb(255, 255, 255)))",
															}}
														>
															{"Text"}
														</motion.p>
													</React.Fragment>
												),
											},
											"ZediBAWvQ-hover": {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-iwvh3s"}
															data-styles-preset={"l6xYtvRSA"}
															style={{
																"--framer-text-alignment": "left",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-2a5ef645-a3a4-4c5f-ba45-e629298b1709, rgb(41, 41, 41)))",
															}}
														>
															{"Text"}
														</motion.p>
													</React.Fragment>
												),
											},
											QOkbEaKc1: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-6qj0qo"}
															data-styles-preset={"PylgTZkRS"}
															style={{
																"--framer-text-alignment": "left",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-4efc64a6-207c-4d82-a4fe-235a43565dac, rgb(61, 61, 61)))",
															}}
														>
															{"Text"}
														</motion.p>
													</React.Fragment>
												),
											},
											TECUXFAwv: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-6qj0qo"}
															data-styles-preset={"PylgTZkRS"}
															style={{
																"--framer-text-alignment": "left",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-2a5ef645-a3a4-4c5f-ba45-e629298b1709, rgb(1, 0, 5)))",
															}}
														>
															{"Text"}
														</motion.p>
													</React.Fragment>
												),
											},
											WllZCZIzo: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-6qj0qo"}
															data-styles-preset={"PylgTZkRS"}
															style={{
																"--framer-text-alignment": "left",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-67ca5fa7-a56e-420c-a780-e11145832d94, rgb(152, 152, 152)))",
															}}
														>
															{"Text"}
														</motion.p>
													</React.Fragment>
												),
											},
											ZediBAWvQ: {
												children: (
													<React.Fragment>
														<motion.p
															className={"framer-styles-preset-iwvh3s"}
															data-styles-preset={"l6xYtvRSA"}
															style={{
																"--framer-text-alignment": "left",
																"--framer-text-color":
																	"var(--extracted-r6o4lv, var(--token-e27967ec-8d88-49ef-9be2-8e921a13da7d, rgb(82, 82, 82)))",
															}}
														>
															{"Text"}
														</motion.p>
													</React.Fragment>
												),
											},
										},
										baseVariant,
										gestureVariant,
									)}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-iwvh3s"}
											data-styles-preset={"l6xYtvRSA"}
											style={{
												"--framer-text-alignment": "left",
												"--framer-text-color":
													"var(--extracted-r6o4lv, rgba(255, 255, 255, 0.7))",
											}}
										>
											{
												"Jl. Halim Perdana Kusuma, Jurumudi Baru, Benda, Kota Tangerang"
											}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
						</motion.a>
					</Link>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-ngZZ6.framer-1b4ujsb, .framer-ngZZ6 .framer-1b4ujsb { display: block; }",
	".framer-ngZZ6.framer-1ch3cf2 { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: hidden; padding: 0px; position: relative; text-decoration: none; width: 277px; }",
	".framer-ngZZ6 .framer-1c1tepx, .framer-ngZZ6 .framer-cou9o9 { flex: none; height: var(--framer-aspect-ratio-supported, 16px); position: relative; width: 16px; }",
	".framer-ngZZ6 .framer-xq94vk { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1px; }",
	".framer-ngZZ6 .framer-1qd6em8 { flex: 1 0 0px; height: auto; position: relative; white-space: pre-wrap; width: 1px; word-break: break-word; word-wrap: break-word; }",
	".framer-ngZZ6.framer-v-570cjb .framer-1c1tepx, .framer-ngZZ6.framer-v-1dra12n .framer-1c1tepx { order: 0; }",
	".framer-ngZZ6.framer-v-570cjb .framer-xq94vk, .framer-ngZZ6.framer-v-1xhsjev .framer-cou9o9, .framer-ngZZ6.framer-v-1g212v0 .framer-cou9o9, .framer-ngZZ6.framer-v-ylwb8w .framer-cou9o9 { order: 1; }",
	".framer-ngZZ6.framer-v-1xhsjev.framer-1ch3cf2 { justify-content: flex-start; }",
	".framer-ngZZ6.framer-v-1xhsjev .framer-xq94vk { flex: none; gap: 8px; height: 24px; justify-content: flex-start; width: 64px; }",
	".framer-ngZZ6.framer-v-1xhsjev .framer-1qd6em8, .framer-ngZZ6.framer-v-1g212v0 .framer-1qd6em8, .framer-ngZZ6.framer-v-ylwb8w .framer-1qd6em8 { flex: none; order: 0; white-space: pre; width: auto; }",
	".framer-ngZZ6.framer-v-1g212v0.framer-1ch3cf2, .framer-ngZZ6.framer-v-ylwb8w.framer-1ch3cf2 { gap: 12px; justify-content: flex-start; width: min-content; }",
	".framer-ngZZ6.framer-v-1g212v0 .framer-xq94vk, .framer-ngZZ6.framer-v-ylwb8w .framer-xq94vk { flex: none; gap: 8px; height: 24px; justify-content: flex-start; width: min-content; }",
	".framer-ngZZ6.framer-v-1dra12n.framer-1ch3cf2 { width: min-content; }",
	".framer-ngZZ6.framer-v-1dra12n .framer-xq94vk { flex: none; order: 1; width: min-content; }",
	".framer-ngZZ6.framer-v-1dra12n .framer-1qd6em8 { flex: none; white-space: pre; width: auto; }",
	...css,
	...css2,
];
var FramerU1GUUBfW3 = withCSS(Component, css3, "framer-ngZZ6");
var stdin_default3 = FramerU1GUUBfW3;
FramerU1GUUBfW3.displayName = "Nav Link without Stack";
FramerU1GUUBfW3.defaultProps = {
	height: 18,
	width: 277,
};
addPropertyControls(FramerU1GUUBfW3, {
	variant: {
		options: [
			"TBuOwI4Yw",
			"rX2dRQW7L",
			"QOkbEaKc1",
			"WllZCZIzo",
			"ZediBAWvQ",
			"TECUXFAwv",
		],
		optionTitles: [
			"sm_white_brand",
			"sm_white_white",
			"md_grey_brand",
			"md_white",
			"sm_grey",
			"Variant 6",
		],
		title: "Variant",
		type: ControlType.Enum,
	},
	huAKLjz4K: {
		title: "Link",
		type: ControlType.Link,
	},
	UwCPZFy3L: {
		defaultValue: "Text",
		displayTextArea: false,
		title: "Text",
		type: ControlType.String,
	},
	B6JoyuVBD: {
		defaultValue: true,
		title: "Show Leading Icon",
		type: ControlType.Boolean,
	},
	Uv1sGVFd3: {
		defaultValue: {
			identifier: "local-module:vector/MZ7RJTDR1:default",
			moduleId: "jLDRGF2znqpCJoBapPHV",
		},
		setModuleId: "5HcY8qtJxbbwKlaxL3rN",
		title: "Leading Icon",
		type: ControlType.VectorSetItem,
	},
	XRG0F6f0o: {
		defaultValue: true,
		title: "Show Trailing Icon",
		type: ControlType.Boolean,
	},
	szA1JNrqU: {
		defaultValue: {
			identifier: "local-module:vector/dZXIZaurD:default",
			moduleId: "lsuNyioxIyDUWMLpauN1",
		},
		setModuleId: "5HcY8qtJxbbwKlaxL3rN",
		title: "Trailing Icon",
		type: ControlType.VectorSetItem,
	},
	ae_saHjca: {
		title: "Click",
		type: ControlType.EventHandler,
	},
});
addFonts(
	FramerU1GUUBfW3,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:nav-link-without-stack
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [
	{
		id: "bvzy1WeYw",
		name: "English",
		slug: "en",
		code: "en",
	},
];
var defaultResponsiveVariants = {
	base: "TECUXFAwv",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"f7de02364badfaa19730b887fe40769babb999f1ad18406989d28f58b996eb79"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default3, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders NavLinkWithoutStackFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"f7de02364badfaa19730b887fe40769babb999f1ad18406989d28f58b996eb79"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default3}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default3);
var nav_link_without_stack_default = ComponentWithRoot;
export { nav_link_without_stack_default as default };
