// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project f7de02364badfaa1 "Roku_ClientHandoff (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * 'en'
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Black_White' | 'Black_Brand' | 'Black only' | 'White_Brand' | 'White only' // Variant
 * applyWhitelist?: string // Apply Whitelist
 * onNCLQfPk3MCHange?: undefined // onNCLQfPk3MCHange
 * click?: Function // Click
 * showIconLeading?: boolean // Show Icon Leading
 * onHKIqfdVxlChange?: undefined // onHKIqfdVxlChange
 * iconLeading?: undefined // Icon Leading
 * colorIconLeading?: string // Color Icon Leading
 * showIconTrailing?: boolean // Show Icon Trailing
 * onkBpjYjKZJChange?: undefined // onkBpjYjKZJChange
 * iconTrailing?: undefined // Icon Trailing
 * colorIconTrailing?: string // Color Icon Trailing
 * link?: string // Link
}} Props

 */
import { stdin_default2 as stdin_default } from "./chunks/chunk-3UJ7YIJM.js";
import { routes } from "./chunks/chunk-VAWW4KIH.js";

// virtual:nav-link-box
import { Fragment } from "react";
import { ContextProviders } from "unframer";
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [
	{
		id: "bvzy1WeYw",
		name: "English",
		slug: "en",
		code: "en",
	},
];
var defaultResponsiveVariants = {
	base: "POzk1uOTE",
	xl: "oSvNCaxnB",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"f7de02364badfaa19730b887fe40769babb999f1ad18406989d28f58b996eb79"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders NavLinkBoxFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"f7de02364badfaa19730b887fe40769babb999f1ad18406989d28f58b996eb79"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var nav_link_box_default = ComponentWithRoot;
export { nav_link_box_default as default };
