// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project f7de02364badfaa1 "Roku_ClientHandoff (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * 'en'
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * title?: string // Title
 * image?: {src: string, srcSet?: string, alt?: string} // Image
 * tag?: string // Tag
 * tagVar?: 'Variant 1' | 'Variant 2' | 'Variant 3' // Tag Var
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-SSFF2S6F.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-UAGVO6ZV.js";
import { routes } from "./chunks/chunk-VAWW4KIH.js";

// virtual:rokumap-item
import { Fragment as Fragment3 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/umeTmrpmwzQhg9dmltgH/3A1410zuWggKKsw8G2Sw/SKCEbozHf.js
import { jsx as _jsx2, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts as addFonts2,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx as cx2,
	getFonts,
	getFontsFromSharedStyle as getFontsFromSharedStyle2,
	getLoadingLazyAtYPosition,
	getPropertyControls,
	Image,
	RichText as RichText2,
	SmartComponentScopedContainer,
	useComponentViewport as useComponentViewport2,
	useLocaleInfo as useLocaleInfo2,
	useVariantState as useVariantState2,
	withCSS as withCSS2,
	withFX,
	withOptimizedAppearEffect,
} from "unframer";
import {
	LayoutGroup as LayoutGroup2,
	motion as motion2,
	MotionConfigContext as MotionConfigContext2,
} from "unframer";
import * as React2 from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/pILwxcxfW50Nl1FlKV1N/8QC0vCuSot5Rnst8PgH1/bjrnGQpkD.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["FR_Gu2PXa", "Q2ezXZEAI", "SiD4i9xKO"];
var serializationHash = "framer-WqBJ5";
var variantClassNames = {
	FR_Gu2PXa: "framer-v-1qb5qw9",
	Q2ezXZEAI: "framer-v-hssjbk",
	SiD4i9xKO: "framer-v-3pc1rm",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Variant 1": "FR_Gu2PXa",
	"Variant 2": "Q2ezXZEAI",
	"Variant 3": "SiD4i9xKO",
};
var getProps = ({ height, id, text, width, ...props }) => {
	return {
		...props,
		mU2ExddDx: text ?? props.mU2ExddDx ?? "Text",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "FR_Gu2PXa",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		mU2ExddDx,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "FR_Gu2PXa",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1qb5qw9",
							className3,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"FR_Gu2PXa"}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-5adf3720-929e-409e-9f09-acc392d4e0f2, rgb(250, 216, 67))",
							borderBottomLeftRadius: 100,
							borderBottomRightRadius: 100,
							borderTopLeftRadius: 100,
							borderTopRightRadius: 100,
							...style,
						}}
						variants={{
							Q2ezXZEAI: {
								backgroundColor:
									"var(--token-329a9c83-6672-4c88-8eb4-e318446a9640, rgb(248, 80, 23))",
							},
							SiD4i9xKO: {
								backgroundColor:
									"var(--token-2a5ef645-a3a4-4c5f-ba45-e629298b1709, rgb(1, 0, 5))",
							},
						}}
						{...addPropertyOverrides(
							{
								Q2ezXZEAI: {
									"data-framer-name": "Variant 2",
								},
								SiD4i9xKO: {
									"data-framer-name": "Variant 3",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-1llue76"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"zrSzf3taN"}
							style={{
								"--extracted-r6o4lv":
									"var(--token-2a5ef645-a3a4-4c5f-ba45-e629298b1709, rgb(1, 0, 5))",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							text={mU2ExddDx}
							variants={{
								Q2ezXZEAI: {
									"--extracted-r6o4lv":
										"var(--token-95cfe971-8e06-4f7f-9e97-f53bf10eec2a, rgb(255, 230, 213))",
								},
								SiD4i9xKO: {
									"--extracted-r6o4lv":
										"var(--token-b0e52b43-0d8f-445a-bc4d-d196172acda5, rgb(36, 183, 253))",
								},
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
							{...addPropertyOverrides(
								{
									Q2ezXZEAI: {
										children: (
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-19tv5pk"}
													data-styles-preset={"U5ucdhln0"}
													style={{
														"--framer-text-alignment": "left",
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-95cfe971-8e06-4f7f-9e97-f53bf10eec2a, rgb(255, 230, 213)))",
													}}
												>
													{"Text"}
												</motion.p>
											</React.Fragment>
										),
									},
									SiD4i9xKO: {
										children: (
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-19tv5pk"}
													data-styles-preset={"U5ucdhln0"}
													style={{
														"--framer-text-alignment": "left",
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-b0e52b43-0d8f-445a-bc4d-d196172acda5, rgb(36, 183, 253)))",
													}}
												>
													{"Text"}
												</motion.p>
											</React.Fragment>
										),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-19tv5pk"}
									data-styles-preset={"U5ucdhln0"}
									style={{
										"--framer-text-alignment": "left",
										"--framer-text-color":
											"var(--extracted-r6o4lv, var(--token-2a5ef645-a3a4-4c5f-ba45-e629298b1709, rgb(1, 0, 5)))",
									}}
								>
									{"Text"}
								</motion.p>
							</React.Fragment>
						</RichText>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-WqBJ5.framer-1n0y06y, .framer-WqBJ5 .framer-1n0y06y { display: block; }",
	".framer-WqBJ5.framer-1qb5qw9 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: 36px; justify-content: center; overflow: hidden; padding: 2px 16px 0px 16px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-WqBJ5 .framer-1llue76 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	...css,
];
var FramerbjrnGQpkD = withCSS(Component, css3, "framer-WqBJ5");
var stdin_default = FramerbjrnGQpkD;
FramerbjrnGQpkD.displayName = "Tags";
FramerbjrnGQpkD.defaultProps = {
	height: 36,
	width: 64,
};
addPropertyControls(FramerbjrnGQpkD, {
	variant: {
		options: ["FR_Gu2PXa", "Q2ezXZEAI", "SiD4i9xKO"],
		optionTitles: ["Variant 1", "Variant 2", "Variant 3"],
		title: "Variant",
		type: ControlType.Enum,
	},
	mU2ExddDx: {
		defaultValue: "Text",
		displayTextArea: false,
		title: "Text",
		type: ControlType.String,
	},
});
addFonts(
	FramerbjrnGQpkD,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// /:https://framerusercontent.com/modules/umeTmrpmwzQhg9dmltgH/3A1410zuWggKKsw8G2Sw/SKCEbozHf.js
var TagsFonts = getFonts(stdin_default);
var RichTextWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(
	withFX(RichText2),
);
var TagsControls = getPropertyControls(stdin_default);
var serializationHash2 = "framer-YZ74G";
var variantClassNames2 = {
	eB0Oe4kAz: "framer-v-1otcxac",
};
var transition12 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transition2 = {
	delay: 0,
	duration: 0.9,
	ease: [0.22, 0.85, 0.56, 1],
	type: "tween",
};
var animation = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 0,
	y: 0,
};
var animation1 = {
	opacity: 1e-3,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 30,
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition2 = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext2);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext2.Provider value={contextValue}>
			{children}
		</MotionConfigContext2.Provider>
	);
};
var Variants2 = motion2.create(React2.Fragment);
var humanReadableEnumMap = {
	"Variant 1": "FR_Gu2PXa",
	"Variant 2": "Q2ezXZEAI",
	"Variant 3": "SiD4i9xKO",
};
var getProps2 = ({
	height,
	id,
	image,
	tag,
	tagVar,
	title,
	width,
	...props
}) => {
	return {
		...props,
		JBDcgb4iF: title ?? props.JBDcgb4iF ?? "Title",
		O9SzjWDG0:
			humanReadableEnumMap[tagVar] ?? tagVar ?? props.O9SzjWDG0 ?? "FR_Gu2PXa",
		whwfh9uwp: tag ?? props.whwfh9uwp ?? "Tag",
		yXePMIgbm: image ?? props.yXePMIgbm,
	};
};
var createLayoutDependency2 = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo2();
	const componentViewport = useComponentViewport2();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		JBDcgb4iF,
		yXePMIgbm,
		whwfh9uwp,
		O9SzjWDG0,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState2({
		defaultVariant: "eB0Oe4kAz",
		ref: refBinding,
		variant,
		variantClassNames: variantClassNames2,
	});
	const layoutDependency = createLayoutDependency2(props, variants);
	const sharedStyleClassNames = [className2];
	const scopingClassNames = cx2(serializationHash2, ...sharedStyleClassNames);
	return (
		<LayoutGroup2 id={layoutId ?? defaultLayoutId}>
			<Variants2 animate={variants} initial={false}>
				<Transition2 value={transition12}>
					<motion2.div
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-1otcxac",
							className3,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"eB0Oe4kAz"}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-a096d81a-91db-425a-b2a9-ca48ac283707, rgb(255, 255, 255))",
							borderBottomLeftRadius: 30,
							borderBottomRightRadius: 30,
							borderTopLeftRadius: 30,
							borderTopRightRadius: 30,
							boxShadow: "0px 4px 10px 0px rgba(0, 0, 0, 0.1)",
							...style,
						}}
					>
						<motion2.div
							className={"framer-il78jl"}
							layoutDependency={layoutDependency}
							layoutId={"zzXwAn_eF"}
						>
							<ComponentViewportProvider
								height={36}
								y={
									(componentViewport?.y || 0) +
									0 +
									(((componentViewport?.height || 412) - 0 - 546) / 2 + 0 + 0) +
									32 +
									0
								}
							>
								<SmartComponentScopedContainer
									className={"framer-hi9hx3-container"}
									layoutDependency={layoutDependency}
									layoutId={"bL5IguRD7-container"}
									nodeId={"bL5IguRD7"}
									rendersWithMotion={true}
									scopeId={"SKCEbozHf"}
								>
									{_jsx2(stdin_default, {
										height: "100%",
										id: "bL5IguRD7",
										layoutId: "bL5IguRD7",
										mU2ExddDx: whwfh9uwp,
										variant: O9SzjWDG0,
										width: "100%",
									})}
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
							<RichTextWithFXWithOptimizedAppearEffect
								__fromCanvasComponent={true}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								animate={animation}
								className={"framer-r9o2mq"}
								data-framer-appear-id={"r9o2mq"}
								fonts={["Inter"]}
								initial={animation1}
								layoutDependency={layoutDependency}
								layoutId={"Yxw5xDbrq"}
								optimized={true}
								text={JBDcgb4iF}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React2.Fragment>
									<motion2.p
										className={"framer-styles-preset-4nmvol"}
										data-styles-preset={"SbGP7ycJT"}
									>
										{"Secure and Decentralized"}
									</motion2.p>
								</React2.Fragment>
							</RichTextWithFXWithOptimizedAppearEffect>
						</motion2.div>
						<motion2.div
							className={"framer-tgge2u"}
							layoutDependency={layoutDependency}
							layoutId={"cSgjgvLXt"}
						>
							<motion2.div
								className={"framer-1v1oq08"}
								layoutDependency={layoutDependency}
								layoutId={"DNeUhS1Gi"}
								style={{
									borderBottomLeftRadius: 20,
									borderBottomRightRadius: 20,
									borderTopLeftRadius: 20,
									borderTopRightRadius: 20,
								}}
							>
								<Image
									background={{
										alt: "",
										fit: "fill",
										intrinsicHeight: 437.52211650878576,
										intrinsicWidth: 489.91149615546885,
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) +
												0 +
												(((componentViewport?.height || 412) - 0 - 546) / 2 +
													252 +
													0) +
												24 +
												0,
										),
										pixelHeight: 618,
										pixelWidth: 692,
										sizes: `max(${componentViewport?.width || "100vw"} - 48px, 1px)`,
										...toResponsiveImage(yXePMIgbm),
									}}
									className={"framer-1yzq8nf"}
									data-framer-name={"Image"}
									layoutDependency={layoutDependency}
									layoutId={"DZB6AVXlG"}
								/>
							</motion2.div>
						</motion2.div>
					</motion2.div>
				</Transition2>
			</Variants2>
		</LayoutGroup2>
	);
});
var css4 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-YZ74G.framer-1gxmbin, .framer-YZ74G .framer-1gxmbin { display: block; }",
	".framer-YZ74G.framer-1otcxac { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 485px; }",
	".framer-YZ74G .framer-il78jl { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: visible; padding: 32px 32px 0px 32px; position: relative; width: 100%; }",
	".framer-YZ74G .framer-hi9hx3-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-YZ74G .framer-r9o2mq { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-YZ74G .framer-tgge2u { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: visible; padding: 24px; position: relative; width: 100%; }",
	".framer-YZ74G .framer-1v1oq08 { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 1px; will-change: var(--framer-will-change-override, transform); }",
	".framer-YZ74G .framer-1yzq8nf { aspect-ratio: 1.7764227642276422 / 1; flex: 1 0 0px; height: var(--framer-aspect-ratio-supported, 246px); overflow: visible; position: relative; width: 1px; }",
	...css2,
];
var FramerSKCEbozHf = withCSS2(Component2, css4, "framer-YZ74G");
var stdin_default2 = FramerSKCEbozHf;
FramerSKCEbozHf.displayName = "Rokumap Item";
FramerSKCEbozHf.defaultProps = {
	height: 412,
	width: 485,
};
addPropertyControls2(FramerSKCEbozHf, {
	JBDcgb4iF: {
		defaultValue: "Title",
		displayTextArea: true,
		title: "Title",
		type: ControlType2.String,
	},
	yXePMIgbm: {
		title: "Image",
		type: ControlType2.ResponsiveImage,
	},
	whwfh9uwp: {
		defaultValue: "Tag",
		displayTextArea: false,
		title: "Tag",
		type: ControlType2.String,
	},
	O9SzjWDG0: TagsControls?.["variant"] && {
		...TagsControls["variant"],
		defaultValue: "FR_Gu2PXa",
		description: void 0,
		hidden: void 0,
		title: "Tag Var",
	},
});
addFonts2(
	FramerSKCEbozHf,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...TagsFonts,
		...getFontsFromSharedStyle2(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:rokumap-item
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [
	{
		id: "bvzy1WeYw",
		name: "English",
		slug: "en",
		code: "en",
	},
];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"f7de02364badfaa19730b887fe40769babb999f1ad18406989d28f58b996eb79"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default2, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders RokumapItemFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"f7de02364badfaa19730b887fe40769babb999f1ad18406989d28f58b996eb79"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default2}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default2);
var rokumap_item_default = ComponentWithRoot;
export { rokumap_item_default as default };
