// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project f7de02364badfaa1 "Roku_ClientHandoff (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * 'en'
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Variant 1' | 'Variant 2' | 'Variant 3' // Variant
 * text?: string // Text
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-SSFF2S6F.js";
import { routes } from "./chunks/chunk-VAWW4KIH.js";

// virtual:tags
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/7m0CqQoknskEsfcLY10m/FuMCz5tI9zZxjfMjfKq3/bjrnGQpkD.js
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = ["FR_Gu2PXa", "Q2ezXZEAI", "SiD4i9xKO"];
var serializationHash = "framer-WqBJ5";
var variantClassNames = {
	FR_Gu2PXa: "framer-v-1qb5qw9",
	Q2ezXZEAI: "framer-v-hssjbk",
	SiD4i9xKO: "framer-v-3pc1rm",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Variant 1": "FR_Gu2PXa",
	"Variant 2": "Q2ezXZEAI",
	"Variant 3": "SiD4i9xKO",
};
var getProps = ({ height, id, text, width, ...props }) => {
	return {
		...props,
		mU2ExddDx: text ?? props.mU2ExddDx ?? "Text",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "FR_Gu2PXa",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		mU2ExddDx,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "FR_Gu2PXa",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1qb5qw9",
							className2,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"FR_Gu2PXa"}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-5adf3720-929e-409e-9f09-acc392d4e0f2, rgb(250, 216, 67))",
							borderBottomLeftRadius: 100,
							borderBottomRightRadius: 100,
							borderTopLeftRadius: 100,
							borderTopRightRadius: 100,
							...style,
						}}
						variants={{
							Q2ezXZEAI: {
								backgroundColor:
									"var(--token-329a9c83-6672-4c88-8eb4-e318446a9640, rgb(248, 80, 23))",
							},
							SiD4i9xKO: {
								backgroundColor:
									"var(--token-2a5ef645-a3a4-4c5f-ba45-e629298b1709, rgb(1, 0, 5))",
							},
						}}
						{...addPropertyOverrides(
							{
								Q2ezXZEAI: {
									"data-framer-name": "Variant 2",
								},
								SiD4i9xKO: {
									"data-framer-name": "Variant 3",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<RichText
							__fromCanvasComponent={true}
							className={"framer-1llue76"}
							fonts={["Inter"]}
							layoutDependency={layoutDependency}
							layoutId={"zrSzf3taN"}
							style={{
								"--extracted-r6o4lv":
									"var(--token-2a5ef645-a3a4-4c5f-ba45-e629298b1709, rgb(1, 0, 5))",
								"--framer-link-text-color": "rgb(0, 153, 255)",
								"--framer-link-text-decoration": "underline",
							}}
							text={mU2ExddDx}
							variants={{
								Q2ezXZEAI: {
									"--extracted-r6o4lv":
										"var(--token-95cfe971-8e06-4f7f-9e97-f53bf10eec2a, rgb(255, 230, 213))",
								},
								SiD4i9xKO: {
									"--extracted-r6o4lv":
										"var(--token-b0e52b43-0d8f-445a-bc4d-d196172acda5, rgb(36, 183, 253))",
								},
							}}
							verticalAlignment={"top"}
							withExternalLayout={true}
							{...addPropertyOverrides(
								{
									Q2ezXZEAI: {
										children: (
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-19tv5pk"}
													data-styles-preset={"U5ucdhln0"}
													style={{
														"--framer-text-alignment": "left",
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-95cfe971-8e06-4f7f-9e97-f53bf10eec2a, rgb(255, 230, 213)))",
													}}
												>
													{"Text"}
												</motion.p>
											</React.Fragment>
										),
									},
									SiD4i9xKO: {
										children: (
											<React.Fragment>
												<motion.p
													className={"framer-styles-preset-19tv5pk"}
													data-styles-preset={"U5ucdhln0"}
													style={{
														"--framer-text-alignment": "left",
														"--framer-text-color":
															"var(--extracted-r6o4lv, var(--token-b0e52b43-0d8f-445a-bc4d-d196172acda5, rgb(36, 183, 253)))",
													}}
												>
													{"Text"}
												</motion.p>
											</React.Fragment>
										),
									},
								},
								baseVariant,
								gestureVariant,
							)}
						>
							<React.Fragment>
								<motion.p
									className={"framer-styles-preset-19tv5pk"}
									data-styles-preset={"U5ucdhln0"}
									style={{
										"--framer-text-alignment": "left",
										"--framer-text-color":
											"var(--extracted-r6o4lv, var(--token-2a5ef645-a3a4-4c5f-ba45-e629298b1709, rgb(1, 0, 5)))",
									}}
								>
									{"Text"}
								</motion.p>
							</React.Fragment>
						</RichText>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-WqBJ5.framer-1n0y06y, .framer-WqBJ5 .framer-1n0y06y { display: block; }",
	".framer-WqBJ5.framer-1qb5qw9 { align-content: center; align-items: center; display: flex; flex-direction: row; flex-wrap: nowrap; gap: 8px; height: 36px; justify-content: center; overflow: hidden; padding: 2px 16px 0px 16px; position: relative; width: min-content; will-change: var(--framer-will-change-override, transform); }",
	".framer-WqBJ5 .framer-1llue76 { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	...css,
];
var FramerbjrnGQpkD = withCSS(Component, css2, "framer-WqBJ5");
var stdin_default = FramerbjrnGQpkD;
FramerbjrnGQpkD.displayName = "Tags";
FramerbjrnGQpkD.defaultProps = {
	height: 36,
	width: 64,
};
addPropertyControls(FramerbjrnGQpkD, {
	variant: {
		options: ["FR_Gu2PXa", "Q2ezXZEAI", "SiD4i9xKO"],
		optionTitles: ["Variant 1", "Variant 2", "Variant 3"],
		title: "Variant",
		type: ControlType.Enum,
	},
	mU2ExddDx: {
		defaultValue: "Text",
		displayTextArea: false,
		title: "Text",
		type: ControlType.String,
	},
});
addFonts(
	FramerbjrnGQpkD,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:tags
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [
	{
		id: "bvzy1WeYw",
		name: "English",
		slug: "en",
		code: "en",
	},
];
var defaultResponsiveVariants = {};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"f7de02364badfaa19730b887fe40769babb999f1ad18406989d28f58b996eb79"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders TagsFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"f7de02364badfaa19730b887fe40769babb999f1ad18406989d28f58b996eb79"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var tags_default = ComponentWithRoot;
export { tags_default as default };
