// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project f7de02364badfaa1 "Roku_ClientHandoff (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * 'en'
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Variant 1' | 'Variant 2' // Variant
 * title?: string // Title
 * description?: string // Description
}} Props

 */
import { className, css, fonts } from "./chunks/chunk-FNBO5TQO.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "./chunks/chunk-UAGVO6ZV.js";
import { routes } from "./chunks/chunk-VAWW4KIH.js";

// virtual:text-2
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/1UowrPIm4jIOavDY0mlu/ujmK40BPEaG3P5e9U6nc/M4yzRXkaS.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
	withOptimizedAppearEffect,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var RichTextWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(
	withFX(RichText),
);
var cycleOrder = ["F0VDmUxFh", "jIzEHs67i"];
var serializationHash = "framer-hCNUV";
var variantClassNames = {
	F0VDmUxFh: "framer-v-4j41kk",
	jIzEHs67i: "framer-v-1up6yto",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transition2 = {
	delay: 0.5,
	duration: 0.9,
	ease: [0.22, 0.85, 0.56, 1],
	type: "tween",
};
var animation = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition2,
	x: 0,
	y: 0,
};
var animation1 = {
	opacity: 1e-3,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 30,
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Variant 1": "F0VDmUxFh",
	"Variant 2": "jIzEHs67i",
};
var getProps = ({ description, height, id, title, width, ...props }) => {
	return {
		...props,
		oHdMK2gLn: title ?? props.oHdMK2gLn ?? "Title",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "F0VDmUxFh",
		yqAEqlZ0o: description ?? props.yqAEqlZ0o ?? "Description",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		oHdMK2gLn,
		yqAEqlZ0o,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "F0VDmUxFh",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className2, className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-4j41kk",
							className3,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"F0VDmUxFh"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-023c0b02-d6e9-49e1-83e1-ac1f4183d641, rgb(234, 236, 245))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							backgroundColor:
								"var(--token-6bb35d22-2ec1-489a-87da-8b723b59a265, rgb(238, 242, 246))",
							borderBottomLeftRadius: 30,
							borderBottomRightRadius: 30,
							borderTopLeftRadius: 30,
							borderTopRightRadius: 30,
							...style,
						}}
						{...addPropertyOverrides(
							{
								jIzEHs67i: {
									"data-framer-name": "Variant 2",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1do6omu"}
							layoutDependency={layoutDependency}
							layoutId={"b4r8NFJch"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-wdy61v"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"A1ZgKXTmZ"}
								text={oHdMK2gLn}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-4nmvol"}
										data-styles-preset={"SbGP7ycJT"}
										style={{
											"--framer-text-alignment": "left",
										}}
									>
										{"Title"}
									</motion.p>
								</React.Fragment>
							</RichText>
							<RichTextWithFXWithOptimizedAppearEffect
								__fromCanvasComponent={true}
								__perspectiveFX={false}
								__smartComponentFX={true}
								__targetOpacity={1}
								animate={animation}
								className={"framer-e2wl55"}
								data-framer-appear-id={"e2wl55"}
								fonts={["Inter"]}
								initial={animation1}
								layoutDependency={layoutDependency}
								layoutId={"Fy3xL8zeg"}
								optimized={true}
								style={{
									"--extracted-r6o4lv":
										"var(--token-2a5ef645-a3a4-4c5f-ba45-e629298b1709, rgb(1, 0, 5))",
								}}
								text={yqAEqlZ0o}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion.p
										className={"framer-styles-preset-6qj0qo"}
										data-styles-preset={"PylgTZkRS"}
										style={{
											"--framer-text-alignment": "left",
											"--framer-text-color":
												"var(--extracted-r6o4lv, var(--token-2a5ef645-a3a4-4c5f-ba45-e629298b1709, rgb(1, 0, 5)))",
										}}
									>
										{
											"Safety is our top concern. Your private keys never leave your non custodial wallet so no one else has access to them, ever. That includes us."
										}
									</motion.p>
								</React.Fragment>
							</RichTextWithFXWithOptimizedAppearEffect>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-hCNUV.framer-r09rhq, .framer-hCNUV .framer-r09rhq { display: block; }",
	".framer-hCNUV.framer-4j41kk { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 24px; height: 334px; justify-content: flex-start; overflow: var(--overflow-clip-fallback, clip); padding: 32px; position: relative; width: 263px; will-change: var(--framer-will-change-override, transform); }",
	".framer-hCNUV .framer-1do6omu { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 8px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 100%; }",
	".framer-hCNUV .framer-wdy61v, .framer-hCNUV .framer-e2wl55 { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-hCNUV.framer-v-1up6yto.framer-4j41kk { height: min-content; }",
	...css2,
	...css,
	'.framer-hCNUV[data-border="true"]::after, .framer-hCNUV [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerM4yzRXkaS = withCSS(Component, css3, "framer-hCNUV");
var stdin_default = FramerM4yzRXkaS;
FramerM4yzRXkaS.displayName = "Text 2";
FramerM4yzRXkaS.defaultProps = {
	height: 226,
	width: 263,
};
addPropertyControls(FramerM4yzRXkaS, {
	variant: {
		options: ["F0VDmUxFh", "jIzEHs67i"],
		optionTitles: ["Variant 1", "Variant 2"],
		title: "Variant",
		type: ControlType.Enum,
	},
	oHdMK2gLn: {
		defaultValue: "Title",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	yqAEqlZ0o: {
		defaultValue: "Description",
		displayTextArea: true,
		title: "Description",
		type: ControlType.String,
	},
});
addFonts(
	FramerM4yzRXkaS,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts2),
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:text-2
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [
	{
		id: "bvzy1WeYw",
		name: "English",
		slug: "en",
		code: "en",
	},
];
var defaultResponsiveVariants = {
	base: "F0VDmUxFh",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"f7de02364badfaa19730b887fe40769babb999f1ad18406989d28f58b996eb79"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders Text2FramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"f7de02364badfaa19730b887fe40769babb999f1ad18406989d28f58b996eb79"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var text_2_default = ComponentWithRoot;
export { text_2_default as default };
