// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project f7de02364badfaa1 "Roku_ClientHandoff (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * 'en'
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'md_outline_white' | 'md_fill_brand' | 'md_fill_accent' | 'md_fit_outline_brand' | 'sm_outline_brand' | 'sm_fill_accent' | 'sm_outline_white' | 'Variant 9' | 'XXL' // Variant
 * title?: string // Title
 * link?: string // Link
 * smoothScroll?: boolean // Smooth Scroll
 * click?: Function // Click
 * hover?: Function // Hover
 * showIconLeading?: boolean // Show Icon Leading
 * iconLeading?: undefined // Icon Leading
 * showIconTrailing?: boolean // Show Icon Trailing
 * iconTrailing?: undefined // Icon Trailing
 * colorIconTrailing?: string // Color Icon Trailing
}} Props

 */
import { stdin_default } from "./chunks/chunk-VZ5XUDHW.js";
import "./chunks/chunk-DYFSM77B.js";
import "./chunks/chunk-U2DM7ILJ.js";
import "./chunks/chunk-FNBO5TQO.js";
import "./chunks/chunk-SSFF2S6F.js";
import { routes } from "./chunks/chunk-VAWW4KIH.js";

// virtual:without-arrow
import { Fragment } from "react";
import { ContextProviders } from "unframer";
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [
	{
		id: "bvzy1WeYw",
		name: "English",
		slug: "en",
		code: "en",
	},
];
var defaultResponsiveVariants = {
	base: "mvqs9WABz",
	xl: "G563AAToD",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"f7de02364badfaa19730b887fe40769babb999f1ad18406989d28f58b996eb79"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders WithoutArrowFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"f7de02364badfaa19730b887fe40769babb999f1ad18406989d28f58b996eb79"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var without_arrow_default = ComponentWithRoot;
export { without_arrow_default as default };
