// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project f7de02364badfaa1 "Roku_ClientHandoff (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * 'en'
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Variant 1' | 'Variant 2' | 'Variant 3' | 'Variant 4' | 'Variant 5' // Variant
}} Props

 */
import { routes } from "../chunks/chunk-VAWW4KIH.js";

// virtual:mockup/phone
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/wtXrBsGCjvxGKSF3JY9t/A89N44Ek5PlwIgCIq8vc/snOGV2n9x.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getLoadingLazyAtYPosition,
	Image,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var cycleOrder = [
	"YjEKllGdu",
	"YTmL9YT_M",
	"HRWYxkKy5",
	"vTvp8Tj9A",
	"w722qumrw",
];
var serializationHash = "framer-m1KVr";
var variantClassNames = {
	HRWYxkKy5: "framer-v-ku388r",
	vTvp8Tj9A: "framer-v-ia319v",
	w722qumrw: "framer-v-19iw1q1",
	YjEKllGdu: "framer-v-ikz21a",
	YTmL9YT_M: "framer-v-1xh1rdg",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 100,
	delay: 0,
	mass: 3,
	stiffness: 500,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Variant 1": "YjEKllGdu",
	"Variant 2": "YTmL9YT_M",
	"Variant 3": "HRWYxkKy5",
	"Variant 4": "vTvp8Tj9A",
	"Variant 5": "w722qumrw",
};
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "YjEKllGdu",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "YjEKllGdu",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.figure
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-ikz21a",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"YjEKllGdu"}
						ref={refBinding}
						style={{
							...style,
						}}
						{...addPropertyOverrides(
							{
								HRWYxkKy5: {
									"data-framer-name": "Variant 3",
								},
								vTvp8Tj9A: {
									"data-framer-name": "Variant 4",
								},
								w722qumrw: {
									"data-framer-name": "Variant 5",
								},
								YTmL9YT_M: {
									"data-framer-name": "Variant 2",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<Image
							background={{
								alt: "",
								fit: "fill",
								intrinsicHeight: 844,
								intrinsicWidth: 390,
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) + 14,
								),
								pixelHeight: 1688,
								pixelWidth: 780,
								sizes: `calc(${componentViewport?.width || "100vw"} - 39px)`,
								src: "https://framerusercontent.com/images/mMsgSuTkNArfwR2hDkIBCqfRyJQ.png?scale-down-to=1024&width=780&height=1688",
								srcSet:
									"https://framerusercontent.com/images/mMsgSuTkNArfwR2hDkIBCqfRyJQ.png?width=780&height=1688 780w",
							}}
							className={"framer-1g9ez5"}
							data-framer-name={"4"}
							layoutDependency={layoutDependency}
							layoutId={"roFhZ2EhT"}
							style={{
								borderBottomLeftRadius: 25,
								borderBottomRightRadius: 25,
								borderTopLeftRadius: 25,
								borderTopRightRadius: 25,
								opacity: 0,
							}}
							variants={{
								w722qumrw: {
									opacity: 1,
								},
							}}
						/>
						<Image
							background={{
								alt: "",
								fit: "fill",
								intrinsicHeight: 844,
								intrinsicWidth: 390,
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) + 14,
								),
								pixelHeight: 1688,
								pixelWidth: 780,
								sizes: `calc(${componentViewport?.width || "100vw"} - 39px)`,
								src: "https://framerusercontent.com/images/nDcCUSshKNpU2LbqeOeEOmbOB3o.png?scale-down-to=1024&width=780&height=1688",
								srcSet:
									"https://framerusercontent.com/images/nDcCUSshKNpU2LbqeOeEOmbOB3o.png?width=780&height=1688 780w",
							}}
							className={"framer-qzblj2"}
							data-framer-name={"0"}
							layoutDependency={layoutDependency}
							layoutId={"VCLPIHa6H"}
							style={{
								borderBottomLeftRadius: 25,
								borderBottomRightRadius: 25,
								borderTopLeftRadius: 25,
								borderTopRightRadius: 25,
								opacity: 1,
							}}
							variants={{
								HRWYxkKy5: {
									opacity: 0,
								},
								vTvp8Tj9A: {
									opacity: 0,
								},
								w722qumrw: {
									opacity: 0,
								},
								YTmL9YT_M: {
									opacity: 0,
								},
							}}
						/>
						<Image
							background={{
								alt: "",
								fit: "fill",
								intrinsicHeight: 844,
								intrinsicWidth: 390,
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) + 14,
								),
								pixelHeight: 1688,
								pixelWidth: 780,
								sizes: `calc(${componentViewport?.width || "100vw"} - 39px)`,
								src: "https://framerusercontent.com/images/FbJlsT2jAxp6KsrSTWutUyJ0emc.png?scale-down-to=1024&width=780&height=1688",
								srcSet:
									"https://framerusercontent.com/images/FbJlsT2jAxp6KsrSTWutUyJ0emc.png?width=780&height=1688 780w",
							}}
							className={"framer-1o5wcf7"}
							data-framer-name={"1"}
							layoutDependency={layoutDependency}
							layoutId={"CKDruZO31"}
							style={{
								borderBottomLeftRadius: 25,
								borderBottomRightRadius: 25,
								borderTopLeftRadius: 25,
								borderTopRightRadius: 25,
								opacity: 0,
							}}
							variants={{
								YTmL9YT_M: {
									opacity: 1,
								},
							}}
						/>
						<Image
							background={{
								alt: "",
								fit: "fill",
								intrinsicHeight: 844,
								intrinsicWidth: 390,
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) + 14,
								),
								pixelHeight: 1688,
								pixelWidth: 780,
								sizes: `calc(${componentViewport?.width || "100vw"} - 39px)`,
								src: "https://framerusercontent.com/images/8ECvjL69MkxVa3f1wbmPZ22fRks.png?scale-down-to=1024&width=780&height=1688",
								srcSet:
									"https://framerusercontent.com/images/8ECvjL69MkxVa3f1wbmPZ22fRks.png?width=780&height=1688 780w",
							}}
							className={"framer-1fx4paq"}
							data-framer-name={"2"}
							layoutDependency={layoutDependency}
							layoutId={"V59d77gYg"}
							style={{
								borderBottomLeftRadius: 25,
								borderBottomRightRadius: 25,
								borderTopLeftRadius: 25,
								borderTopRightRadius: 25,
								opacity: 0,
							}}
							variants={{
								HRWYxkKy5: {
									opacity: 1,
								},
							}}
						/>
						<Image
							background={{
								alt: "",
								fit: "fill",
								intrinsicHeight: 844,
								intrinsicWidth: 390,
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) + 14,
								),
								pixelHeight: 1688,
								pixelWidth: 780,
								sizes: `calc(${componentViewport?.width || "100vw"} - 39px)`,
								src: "https://framerusercontent.com/images/bSufdlDLsG5vJX8ZsCNV8kP6k.png?scale-down-to=1024&width=780&height=1688",
								srcSet:
									"https://framerusercontent.com/images/bSufdlDLsG5vJX8ZsCNV8kP6k.png?width=780&height=1688 780w",
							}}
							className={"framer-122mg02"}
							data-framer-name={"3"}
							layoutDependency={layoutDependency}
							layoutId={"gXXBoeDM4"}
							style={{
								borderBottomLeftRadius: 25,
								borderBottomRightRadius: 25,
								borderTopLeftRadius: 25,
								borderTopRightRadius: 25,
								opacity: 0,
							}}
							variants={{
								vTvp8Tj9A: {
									opacity: 1,
								},
							}}
						/>
						<Image
							background={{
								alt: "",
								fit: "fill",
								intrinsicHeight: 735,
								intrinsicWidth: 361,
								loading: getLoadingLazyAtYPosition(
									(componentViewport?.y || 0) + 0,
								),
								pixelHeight: 1470,
								pixelWidth: 722,
								src: "https://framerusercontent.com/images/YlYIbfFEujexwgWABDzpsRlY.webp?width=722&height=1470",
							}}
							className={"framer-1qtsp7h"}
							data-framer-name={"iPhone"}
							layoutDependency={layoutDependency}
							layoutId={"lPnjyYYYH"}
						/>
					</motion.figure>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-m1KVr.framer-z3093z, .framer-m1KVr .framer-z3093z { display: block; }",
	".framer-m1KVr.framer-ikz21a { gap: 0px; height: 688px; overflow: visible; position: relative; width: 342px; }",
	".framer-m1KVr .framer-1g9ez5, .framer-m1KVr .framer-qzblj2, .framer-m1KVr .framer-1o5wcf7, .framer-m1KVr .framer-1fx4paq, .framer-m1KVr .framer-122mg02 { bottom: 14px; flex: none; left: 20px; overflow: visible; position: absolute; right: 19px; top: 14px; }",
	".framer-m1KVr .framer-1qtsp7h { bottom: 1px; flex: none; left: 2px; overflow: visible; position: absolute; right: 2px; top: 0px; }",
	".framer-m1KVr.framer-v-1xh1rdg.framer-ikz21a, .framer-m1KVr.framer-v-ku388r.framer-ikz21a, .framer-m1KVr.framer-v-ia319v.framer-ikz21a, .framer-m1KVr.framer-v-19iw1q1.framer-ikz21a { aspect-ratio: 0.4963609898107715 / 1; height: var(--framer-aspect-ratio-supported, 689px); }",
];
var FramersnOGV2n9x = withCSS(Component, css, "framer-m1KVr");
var stdin_default = FramersnOGV2n9x;
FramersnOGV2n9x.displayName = "Mockup/Phone";
FramersnOGV2n9x.defaultProps = {
	height: 689,
	width: 342,
};
addPropertyControls(FramersnOGV2n9x, {
	variant: {
		options: ["YjEKllGdu", "YTmL9YT_M", "HRWYxkKy5", "vTvp8Tj9A", "w722qumrw"],
		optionTitles: [
			"Variant 1",
			"Variant 2",
			"Variant 3",
			"Variant 4",
			"Variant 5",
		],
		title: "Variant",
		type: ControlType.Enum,
	},
});
addFonts(
	FramersnOGV2n9x,
	[
		{
			explicitInter: true,
			fonts: [],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:mockup/phone
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [
	{
		id: "bvzy1WeYw",
		name: "English",
		slug: "en",
		code: "en",
	},
];
var defaultResponsiveVariants = {
	base: "YjEKllGdu",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"f7de02364badfaa19730b887fe40769babb999f1ad18406989d28f58b996eb79"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders PhoneFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"f7de02364badfaa19730b887fe40769babb999f1ad18406989d28f58b996eb79"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var phone_default = ComponentWithRoot;
export { phone_default as default };
