// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project f7de02364badfaa1 "Roku_ClientHandoff (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * 'en'
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Variant 1' | 'Variant 2' // Variant
 * image?: {src: string, srcSet?: string, alt?: string} // Image
 * title?: string // Title
 * date?: string // Date
}} Props

 */
import { className, css, fonts } from "../chunks/chunk-U2DM7ILJ.js";
import {
	className as className2,
	css as css2,
	fonts as fonts2,
} from "../chunks/chunk-UMPRUBXN.js";
import { routes } from "../chunks/chunk-VAWW4KIH.js";

// virtual:card/blog
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/v74zbJpmDOMqlqRL8TZd/4Ec738FRTvdOkVNQuKHW/rxbG6tKVg.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls,
	ControlType,
	cx,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef } from "react";
var enabledGestures = {
	cpHz5tzQS: {
		hover: true,
	},
};
var cycleOrder = ["cpHz5tzQS", "pA_HgAw2L"];
var serializationHash = "framer-IRx6m";
var variantClassNames = {
	cpHz5tzQS: "framer-v-1iepg3l",
	pA_HgAw2L: "framer-v-i8vwy",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	damping: 100,
	delay: 0,
	mass: 3,
	stiffness: 500,
	type: "spring",
};
var toResponsiveImage = (value) => {
	if (
		typeof value === "object" &&
		value !== null &&
		typeof value.src === "string"
	) {
		return value;
	}
	return typeof value === "string"
		? {
				src: value,
			}
		: void 0;
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = {
	"Variant 1": "cpHz5tzQS",
	"Variant 2": "pA_HgAw2L",
};
var getProps = ({ date, height, id, image, title, width, ...props }) => {
	return {
		...props,
		AzbhVAkk6: title ?? props.AzbhVAkk6 ?? "Title",
		J1e1yscGw: image ??
			props.J1e1yscGw ?? {
				alt: "",
				pixelHeight: 1440,
				pixelWidth: 2560,
				src: "https://framerusercontent.com/images/wJDHFnlIyHLTMsKqUw4VXU1JUGg.png?scale-down-to=512&width=2560&height=1440",
				srcSet:
					"https://framerusercontent.com/images/wJDHFnlIyHLTMsKqUw4VXU1JUGg.png?scale-down-to=512&width=2560&height=1440 512w,https://framerusercontent.com/images/wJDHFnlIyHLTMsKqUw4VXU1JUGg.png?scale-down-to=1024&width=2560&height=1440 1024w,https://framerusercontent.com/images/wJDHFnlIyHLTMsKqUw4VXU1JUGg.png?scale-down-to=2048&width=2560&height=1440 2048w,https://framerusercontent.com/images/wJDHFnlIyHLTMsKqUw4VXU1JUGg.png?width=2560&height=1440 2560w",
			},
		kI_oIhwNs: date ?? props.kI_oIhwNs ?? "Date",
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "cpHz5tzQS",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className3,
		layoutId,
		variant,
		J1e1yscGw,
		AzbhVAkk6,
		kI_oIhwNs,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "cpHz5tzQS",
		enabledGestures,
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className, className2];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-1iepg3l",
							className3,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"cpHz5tzQS"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color":
								"var(--token-023c0b02-d6e9-49e1-83e1-ac1f4183d641, rgb(227, 232, 239))",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							backgroundColor:
								"var(--token-8ac42f33-b461-440e-a9af-a56ecc86f907, rgb(248, 250, 252))",
							borderBottomLeftRadius: 30,
							borderBottomRightRadius: 30,
							borderTopLeftRadius: 30,
							borderTopRightRadius: 30,
							...style,
						}}
						variants={{
							"cpHz5tzQS-hover": {
								backgroundColor:
									"var(--token-6bb35d22-2ec1-489a-87da-8b723b59a265, rgb(238, 242, 246))",
							},
						}}
						{...addPropertyOverrides(
							{
								"cpHz5tzQS-hover": {
									"data-framer-name": void 0,
								},
								pA_HgAw2L: {
									"data-framer-name": "Variant 2",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion.div
							className={"framer-1od5has"}
							layoutDependency={layoutDependency}
							layoutId={"t_JKcIeN4"}
						>
							<motion.div
								className={"framer-1p7f36r"}
								layoutDependency={layoutDependency}
								layoutId={"yQXnsJ53P"}
								style={{
									borderBottomLeftRadius: 20,
									borderBottomRightRadius: 20,
									borderTopLeftRadius: 20,
									borderTopRightRadius: 20,
								}}
							>
								<Image
									background={{
										alt: "",
										fit: "fill",
										intrinsicHeight: 203.893801868172,
										intrinsicWidth: 362.4778699878613,
										loading: getLoadingLazyAtYPosition(
											(componentViewport?.y || 0) +
												0 +
												(((componentViewport?.height || 322) - 0 - 498) / 2 +
													0 +
													0) +
												8 +
												0,
										),
										pixelHeight: 1440,
										pixelWidth: 2560,
										sizes: `max(${componentViewport?.width || "100vw"} - 16px, 1px)`,
										...toResponsiveImage(J1e1yscGw),
									}}
									className={"framer-2b5rv2"}
									data-framer-name={"Image"}
									layoutDependency={layoutDependency}
									layoutId={"zbm6ttVZI"}
									style={{
										scale: 1,
									}}
									variants={{
										"cpHz5tzQS-hover": {
											scale: 1.1,
										},
									}}
								/>
							</motion.div>
						</motion.div>
						<motion.div
							className={"framer-w462hr"}
							layoutDependency={layoutDependency}
							layoutId={"FrgQ0JGlX"}
						>
							<motion.div
								className={"framer-1aai4qg"}
								layoutDependency={layoutDependency}
								layoutId={"Yj7tS1X4A"}
							>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-d36ve6"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"S7nkDpyXz"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-0d09ba75-26a4-4e48-a43d-731b581e642d, rgb(41, 48, 86))",
									}}
									text={AzbhVAkk6}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-192lay5"}
											data-styles-preset={"Ep4_CVgrF"}
											style={{
												"--framer-text-alignment": "left",
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-0d09ba75-26a4-4e48-a43d-731b581e642d, rgb(41, 48, 86)))",
											}}
										>
											{"Title"}
										</motion.p>
									</React.Fragment>
								</RichText>
								<RichText
									__fromCanvasComponent={true}
									className={"framer-19mhc9s"}
									fonts={["Inter"]}
									layoutDependency={layoutDependency}
									layoutId={"xqnpW6L96"}
									style={{
										"--extracted-r6o4lv":
											"var(--token-67ca5fa7-a56e-420c-a780-e11145832d94, rgb(154, 164, 178))",
									}}
									text={kI_oIhwNs}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React.Fragment>
										<motion.p
											className={"framer-styles-preset-iwvh3s"}
											data-styles-preset={"l6xYtvRSA"}
											style={{
												"--framer-text-alignment": "left",
												"--framer-text-color":
													"var(--extracted-r6o4lv, var(--token-67ca5fa7-a56e-420c-a780-e11145832d94, rgb(154, 164, 178)))",
											}}
										>
											{"Date"}
										</motion.p>
									</React.Fragment>
								</RichText>
							</motion.div>
						</motion.div>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-IRx6m.framer-gmh9v4, .framer-IRx6m .framer-gmh9v4 { display: block; }",
	".framer-IRx6m.framer-1iepg3l { align-content: center; align-items: center; cursor: pointer; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 389px; will-change: var(--framer-will-change-override, transform); }",
	".framer-IRx6m .framer-1od5has { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 8px; position: relative; width: 100%; }",
	".framer-IRx6m .framer-1p7f36r { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 1px; will-change: var(--framer-will-change-override, transform); }",
	".framer-IRx6m .framer-2b5rv2 { aspect-ratio: 1.7777777777777777 / 1; flex: 1 0 0px; height: var(--framer-aspect-ratio-supported, 210px); overflow: visible; position: relative; width: 1px; }",
	".framer-IRx6m .framer-w462hr { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 16px; height: min-content; justify-content: center; overflow: var(--overflow-clip-fallback, clip); padding: 24px; position: relative; width: 100%; }",
	".framer-IRx6m .framer-1aai4qg { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 100%; }",
	".framer-IRx6m .framer-d36ve6, .framer-IRx6m .framer-19mhc9s { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-IRx6m.framer-v-i8vwy.framer-1iepg3l { cursor: unset; min-height: 264px; }",
	...css,
	...css2,
	'.framer-IRx6m[data-border="true"]::after, .framer-IRx6m [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; pointer-events: none; }',
];
var FramerrxbG6tKVg = withCSS(Component, css3, "framer-IRx6m");
var stdin_default = FramerrxbG6tKVg;
FramerrxbG6tKVg.displayName = "Card/Blog";
FramerrxbG6tKVg.defaultProps = {
	height: 322,
	width: 389,
};
addPropertyControls(FramerrxbG6tKVg, {
	variant: {
		options: ["cpHz5tzQS", "pA_HgAw2L"],
		optionTitles: ["Variant 1", "Variant 2"],
		title: "Variant",
		type: ControlType.Enum,
	},
	J1e1yscGw: {
		__defaultAssetReference:
			"data:framer/asset-reference,wJDHFnlIyHLTMsKqUw4VXU1JUGg.png?originalFilename=image.png&preferredSize=auto&width=2560&height=1440",
		__vekterDefault: {
			alt: "",
			assetReference:
				"data:framer/asset-reference,wJDHFnlIyHLTMsKqUw4VXU1JUGg.png?originalFilename=image.png&preferredSize=auto&width=2560&height=1440",
		},
		title: "Image",
		type: ControlType.ResponsiveImage,
	},
	AzbhVAkk6: {
		defaultValue: "Title",
		displayTextArea: false,
		title: "Title",
		type: ControlType.String,
	},
	kI_oIhwNs: {
		defaultValue: "Date",
		title: "Date",
		type: ControlType.String,
	},
});
addFonts(
	FramerrxbG6tKVg,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
			],
		},
		...getFontsFromSharedStyle(fonts),
		...getFontsFromSharedStyle(fonts2),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:card/blog
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [
	{
		id: "bvzy1WeYw",
		name: "English",
		slug: "en",
		code: "en",
	},
];
var defaultResponsiveVariants = {
	base: "pA_HgAw2L",
	xl: "cpHz5tzQS",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"f7de02364badfaa19730b887fe40769babb999f1ad18406989d28f58b996eb79"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders BlogFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"f7de02364badfaa19730b887fe40769babb999f1ad18406989d28f58b996eb79"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var blog_default = ComponentWithRoot;
export { blog_default as default };
