// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project f7de02364badfaa1 "Roku_ClientHandoff (copy)", do not edit manually */
"use client";

/**
 * @typedef Locale
 * 'en'
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Variant 1' | 'Variant 2' // Variant
 * label?: string // Label
 * end?: number // End
 * suffix?: string // Suffix
 * prefix?: string // Prefix
 * decimals?: 'Off' | '1' | '2' | '3' // Decimals
}} Props

 */
import { routes } from "../chunks/chunk-VAWW4KIH.js";

// virtual:card/features-2
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/cSPDaXECNN4iM3MawaIm/vVW8W3qp0SuIKExBtTeu/n_UbZOK3s.js
import { jsx as _jsx, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx,
	getFonts,
	getFontsFromSharedStyle,
	getPropertyControls,
	RichText,
	SmartComponentScopedContainer,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
} from "unframer";
import { LayoutGroup, motion as motion2, MotionConfigContext } from "unframer";
import * as React from "react";
import { useRef as useRef2 } from "react";

// /:https://framerusercontent.com/modules/qpjhCcDm4G1NbFAlpMKV/OnyZiTlIjOBuSKcKQWFv/AnimatedNumberCounter_Prod.js
import { jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { addPropertyControls, ControlType, RenderTarget } from "unframer";
import { useEffect, useState, useRef } from "react";
import { motion, useMotionValue, animate, useInView } from "unframer";
function AnimatedNumberCounter(props) {
	const { mode, start, end, value, decimals, commas, color, animation } = props;
	const isCanvas = RenderTarget.current() === RenderTarget.canvas;
	const Tag = props.tag;
	const MotionTag = motion[props.tag];
	const isDefault = mode == "default";
	const initialValue = isDefault ? start : value;
	const transition = isDefault ? animation.transition : props.transition;
	const formatNumber = (number2) => {
		let numberString = number2.toFixed(decimals);
		if (commas) {
			numberString = numberString.replace(/\B(?=(\d{3})+(?!\d))/g, ",");
		}
		return numberString;
	};
	const [number, setNumber] = useState(initialValue);
	const [finalValue, setFinalValue] = useState(number);
	const [currentAnimation, setCurrentAnimation] = useState(null);
	const ref = useRef(null);
	const isInView = useInView(ref, {
		once: !props.animation.replay,
		amount: "some",
	});
	const motionValue = useMotionValue(value);
	const runAnimation = (from, to) => {
		if (!isCanvas) {
			if (currentAnimation) {
				currentAnimation.stop();
			}
			setFinalValue(to);
			setCurrentAnimation(
				animate(from, to, {
					...transition,
					onUpdate: (latest) => {
						setNumber(latest);
					},
				}),
			);
		}
	};
	useEffect(() => {
		if (isDefault && animation.trigger == "appear") {
			runAnimation(start, end);
		}
	}, []);
	useEffect(() => {
		if (isDefault && animation.trigger == "layerInView") {
			if (isInView) {
				runAnimation(start, end);
			} else {
				if (currentAnimation) {
					currentAnimation.stop();
				}
				setNumber(start);
			}
		}
	}, [isInView]);
	useEffect(() => {
		if (!isDefault) {
			runAnimation(number, value);
		}
	}, [value]);
	return (
		<_Fragment>
			<Tag
				style={{
					...props.style,
					margin: 0,
					opacity: 0,
					pointerEvents: "none",
					userSelect: "none",
					textWrap: props.balance ? "balance" : void 0,
					fontVariantNumeric: props.monospace ? "tabular-nums" : void 0,
					textAlign: "center",
					...props.font,
				}}
			>
				{props.prefix}
				{formatNumber(isCanvas ? initialValue : finalValue)}
				{props.suffix}
			</Tag>
			<MotionTag
				ref={ref}
				style={{
					position: "absolute",
					inset: 0,
					userSelect: props.userSelect ? "auto" : "none",
					fontVariantNumeric: props.monospace ? "tabular-nums" : void 0,
					margin: 0,
					...(color.mode == "solid"
						? {
								color: color.color,
							}
						: {
								WebkitBackgroundClip: "text",
								WebkitTextFillColor: "transparent",
								backgroundImage: `linear-gradient(${color.angle}deg, ${color.startColor}, ${color.endColor})`,
							}),
					textDecoration: props.decoration,
					textWrap: props.balance ? "balance" : void 0,
					textAlign: "center",
					...props.font,
					...props.style,
				}}
			>
				{props.prefix}
				{formatNumber(isCanvas ? initialValue : number)}
				{props.suffix}
			</MotionTag>
		</_Fragment>
	);
}
AnimatedNumberCounter.displayName = "Animated Number Counter";
addPropertyControls(AnimatedNumberCounter, {
	mode: {
		type: ControlType.Enum,
		options: ["default", "variants"],
		optionTitles: ["Default", "Variants"],
		displaySegmentedControl: true,
	},
	value: {
		type: ControlType.Number,
		defaultValue: 0,
		hidden: (props) => props.mode !== "variants",
	},
	start: {
		type: ControlType.Number,
		defaultValue: 0,
		hidden: (props) => props.mode !== "default",
	},
	end: {
		type: ControlType.Number,
		defaultValue: 100,
		hidden: (props) => props.mode !== "default",
	},
	animation: {
		type: ControlType.Object,
		icon: "effect",
		hidden: (props) => props.mode !== "default",
		controls: {
			trigger: {
				type: ControlType.Enum,
				defaultValue: "layerInView",
				options: ["appear", "layerInView"],
				optionTitles: ["Appear", "Layer in View"],
				displaySegmentedControl: true,
				segmentedControlDirection: "vertical",
			},
			replay: {
				type: ControlType.Boolean,
				defaultValue: true,
				hidden(props) {
					return props.trigger !== "layerInView";
				},
			},
			transition: {
				type: ControlType.Transition,
				defaultValue: {
					type: "spring",
					duration: 1,
					bounce: 0,
				},
			},
		},
	},
	transition: {
		type: ControlType.Transition,
		defaultValue: {
			type: "spring",
			duration: 1,
			bounce: 0,
		},
		hidden: (props) => props.mode !== "variants",
	},
	decimals: {
		type: ControlType.Enum,
		defaultValue: 0,
		options: [0, 1, 2, 3],
		optionTitles: ["Off", "1", "2", "3"],
		displaySegmentedControl: true,
	},
	commas: {
		type: ControlType.Boolean,
		defaultValue: true,
	},
	font: {
		type: "font",
		controls: "extended",
		defaultFontType: "sans-serif",
		defaultValue: {
			fontSize: 16,
			lineHeight: 1,
		},
	},
	color: {
		type: ControlType.Object,
		controls: {
			mode: {
				type: ControlType.Enum,
				defaultValue: "solid",
				options: ["solid", "gradient"],
				optionTitles: ["Solid", "Gradient"],
				displaySegmentedControl: true,
			},
			color: {
				type: ControlType.Color,
				defaultValue: "#000",
				hidden: (props) => props.mode !== "solid",
			},
			startColor: {
				type: ControlType.Color,
				defaultValue: "#000",
				hidden: (props) => props.mode !== "gradient",
			},
			endColor: {
				type: ControlType.Color,
				defaultValue: "#FFF",
				hidden: (props) => props.mode !== "gradient",
			},
			angle: {
				type: ControlType.Number,
				defaultValue: 180,
				min: -360,
				max: 360,
				unit: "\xB0",
				hidden: (props) => props.mode !== "gradient",
			},
		},
	},
	prefix: {
		type: ControlType.String,
		placeholder: "Prefix",
	},
	suffix: {
		type: ControlType.String,
		placeholder: "Suffix",
	},
	decoration: {
		type: ControlType.Enum,
		defaultValue: "none",
		options: ["none", "underline", "line-through"],
		optionTitles: ["None", "Underline", "Strikethrough"],
	},
	balance: {
		type: ControlType.Boolean,
		defaultValue: false,
	},
	userSelect: {
		type: ControlType.Boolean,
		defaultValue: true,
	},
	tag: {
		type: ControlType.Enum,
		defaultValue: "p",
		displaySegmentedControl: true,
		options: ["h1", "h2", "h3", "p"],
		optionTitles: ["H1", "H2", "H3", "P"],
	},
	monospace: {
		type: ControlType.Boolean,
		defaultValue: false,
		description:
			"More components at [Framer University](https://frameruni.link/cc).",
	},
});

// /:https://framerusercontent.com/modules/47YCaQwGLJmOP105TSVa/p02l0cRq4ES2oRAgIIeS/JhkM3yB6E.js
import { fontStore } from "unframer";
fontStore.loadFonts(["CUSTOM;Allotrope Medium"]);
var fonts = [
	{
		explicitInter: true,
		fonts: [
			{
				family: "Allotrope Medium",
				source: "custom",
				url: "https://framerusercontent.com/assets/6okJgJq4QB9lJXMD6PCTr3rikbA.woff2",
			},
		],
	},
];
var css = [
	'.framer-Dz2E6 .framer-styles-preset-1fbpzch:not(.rich-text-wrapper), .framer-Dz2E6 .framer-styles-preset-1fbpzch.rich-text-wrapper p { --framer-font-family: "Allotrope Medium", sans-serif; --framer-font-open-type-features: normal; --framer-font-size: 18px; --framer-font-style: normal; --framer-font-variation-axes: normal; --framer-font-weight: 400; --framer-letter-spacing: 0px; --framer-line-height: 120%; --framer-paragraph-spacing: 20px; --framer-text-alignment: start; --framer-text-color: var(--token-4efc64a6-207c-4d82-a4fe-235a43565dac, #181d27); --framer-text-decoration: none; --framer-text-stroke-color: initial; --framer-text-stroke-width: initial; --framer-text-transform: none; }',
];
var className = "framer-Dz2E6";

// /:https://framerusercontent.com/modules/cSPDaXECNN4iM3MawaIm/vVW8W3qp0SuIKExBtTeu/n_UbZOK3s.js
var AnimatedNumberCounterFonts = getFonts(AnimatedNumberCounter);
var AnimatedNumberCounterControls = getPropertyControls(AnimatedNumberCounter);
var cycleOrder = ["SmW3Sw4UK", "sVo4L48mS"];
var serializationHash = "framer-8aEi9";
var variantClassNames = {
	SmW3Sw4UK: "framer-v-a97owt",
	sVo4L48mS: "framer-v-1yovm9e",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider value={contextValue}>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion2.create(React.Fragment);
var humanReadableEnumMap = {};
var humanReadableVariantMap = {
	"Variant 1": "SmW3Sw4UK",
	"Variant 2": "sVo4L48mS",
};
var getProps = ({
	decimals,
	end,
	height,
	id,
	label,
	prefix,
	suffix,
	width,
	...props
}) => {
	return {
		...props,
		DdH0JeJ9D: end ?? props.DdH0JeJ9D ?? 56,
		JRzzwo6zt: label ?? props.JRzzwo6zt ?? "Label",
		qAt6ppb0h: prefix ?? props.qAt6ppb0h,
		tAuXJS9mE: suffix ?? props.tAuXJS9mE,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "SmW3Sw4UK",
		XK1CMv3jr: humanReadableEnumMap[decimals] ?? decimals ?? props.XK1CMv3jr,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		JRzzwo6zt,
		DdH0JeJ9D,
		tAuXJS9mE,
		qAt6ppb0h,
		XK1CMv3jr,
		...restProps
	} = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "SmW3Sw4UK",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup id={layoutId ?? defaultLayoutId}>
			<Variants animate={variants} initial={false}>
				<Transition value={transition1}>
					<motion2.div
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-a97owt",
							className2,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"SmW3Sw4UK"}
						ref={refBinding}
						style={{
							backgroundColor:
								"var(--token-329a9c83-6672-4c88-8eb4-e318446a9640, rgb(248, 80, 23))",
							borderBottomLeftRadius: 30,
							borderBottomRightRadius: 30,
							borderTopLeftRadius: 30,
							borderTopRightRadius: 30,
							...style,
						}}
						{...addPropertyOverrides(
							{
								sVo4L48mS: {
									"data-framer-name": "Variant 2",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion2.div
							className={"framer-1w1rumw"}
							layoutDependency={layoutDependency}
							layoutId={"vecGLEKpl"}
						>
							<RichText
								__fromCanvasComponent={true}
								className={"framer-rncb2y"}
								fonts={["Inter"]}
								layoutDependency={layoutDependency}
								layoutId={"SAfz4ZBHW"}
								style={{
									"--extracted-1w3ko1f":
										"var(--token-a096d81a-91db-425a-b2a9-ca48ac283707, rgb(255, 255, 255))",
								}}
								text={JRzzwo6zt}
								verticalAlignment={"top"}
								withExternalLayout={true}
							>
								<React.Fragment>
									<motion2.p
										className={"framer-styles-preset-1fbpzch"}
										data-styles-preset={"JhkM3yB6E"}
									>
										<motion2.span
											style={{
												"--framer-text-color":
													"var(--extracted-1w3ko1f, var(--token-a096d81a-91db-425a-b2a9-ca48ac283707, rgb(255, 255, 255)))",
											}}
										>
											{"PnL and Position Tracking"}
										</motion2.span>
										<motion2.br />
										<motion2.br className={"trailing-break"} />
									</motion2.p>
								</React.Fragment>
							</RichText>
							<ComponentViewportProvider>
								<SmartComponentScopedContainer
									className={"framer-1obb7bk-container"}
									isAuthoredByUser={true}
									isModuleExternal={true}
									layoutDependency={layoutDependency}
									layoutId={"qWXLMTKx8-container"}
									nodeId={"qWXLMTKx8"}
									rendersWithMotion={true}
									scopeId={"n_UbZOK3s"}
								>
									<AnimatedNumberCounter
										animation={{
											replay: true,
											transition: {
												bounce: 0,
												delay: 0,
												duration: 1,
												type: "spring",
											},
											trigger: "layerInView",
										}}
										balance={false}
										color={{
											angle: 180,
											color:
												"var(--token-a096d81a-91db-425a-b2a9-ca48ac283707, rgb(255, 255, 255))",
											endColor: "rgb(255, 255, 255)",
											mode: "solid",
											startColor: "rgb(0, 0, 0)",
										}}
										commas={true}
										decimals={XK1CMv3jr}
										decoration={"none"}
										end={DdH0JeJ9D}
										font={{
											fontFamily:
												'"FONTSPRING DEMO - Allotrope Bold", sans-serif',
											fontSize: "56px",
											letterSpacing: "0em",
											lineHeight: "1.2em",
											textAlign: "left",
										}}
										height={"100%"}
										id={"qWXLMTKx8"}
										layoutId={"qWXLMTKx8"}
										mode={"default"}
										monospace={false}
										prefix={qAt6ppb0h}
										start={0}
										style={{
											width: "100%",
										}}
										suffix={tAuXJS9mE}
										tag={"p"}
										transition={{
											bounce: 0,
											delay: 0,
											duration: 1,
											type: "spring",
										}}
										userSelect={false}
										value={0}
										width={"100%"}
										{...addPropertyOverrides(
											{
												sVo4L48mS: {
													font: {
														fontFamily:
															'"FONTSPRING DEMO - Allotrope Bold", sans-serif',
														fontSize: "40px",
														letterSpacing: "0em",
														lineHeight: "1.2em",
														textAlign: "left",
													},
												},
											},
											baseVariant,
											gestureVariant,
										)}
									/>
								</SmartComponentScopedContainer>
							</ComponentViewportProvider>
						</motion2.div>
					</motion2.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css2 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-8aEi9.framer-dxzxdf, .framer-8aEi9 .framer-dxzxdf { display: block; }",
	".framer-8aEi9.framer-a97owt { align-content: flex-start; align-items: flex-start; display: flex; flex-direction: column; flex-wrap: nowrap; height: 250px; justify-content: space-between; min-height: 250px; overflow: var(--overflow-clip-fallback, clip); padding: 24px; position: relative; width: 432px; will-change: var(--framer-will-change-override, transform); }",
	".framer-8aEi9 .framer-1w1rumw { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; height: 1px; justify-content: space-between; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 100%; }",
	".framer-8aEi9 .framer-rncb2y { flex: none; height: auto; position: relative; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-8aEi9 .framer-1obb7bk-container { flex: none; height: auto; position: relative; width: 100%; }",
	...css,
];
var Framern_UbZOK3s = withCSS(Component, css2, "framer-8aEi9");
var stdin_default = Framern_UbZOK3s;
Framern_UbZOK3s.displayName = "Card/Features 2";
Framern_UbZOK3s.defaultProps = {
	height: 250,
	width: 432,
};
addPropertyControls2(Framern_UbZOK3s, {
	variant: {
		options: ["SmW3Sw4UK", "sVo4L48mS"],
		optionTitles: ["Variant 1", "Variant 2"],
		title: "Variant",
		type: ControlType2.Enum,
	},
	JRzzwo6zt: {
		defaultValue: "Label",
		title: "Label",
		type: ControlType2.String,
	},
	DdH0JeJ9D: {
		defaultValue: 56,
		title: "End",
		type: ControlType2.Number,
	},
	tAuXJS9mE: {
		defaultValue: "",
		placeholder: "Suffix",
		title: "Suffix",
		type: ControlType2.String,
	},
	qAt6ppb0h: {
		defaultValue: "",
		placeholder: "Prefix",
		title: "Prefix",
		type: ControlType2.String,
	},
	XK1CMv3jr: AnimatedNumberCounterControls?.["decimals"] && {
		...AnimatedNumberCounterControls["decimals"],
		defaultValue: 0,
		description: void 0,
		hidden: void 0,
		title: "Decimals",
	},
});
addFonts(
	Framern_UbZOK3s,
	[
		{
			explicitInter: true,
			fonts: [
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/5vvr9Vy74if2I6bQbJvbw7SY1pQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/EOr0mi4hNtlgWNn9if640EZzXCo.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/Y9k9QrlZAqio88Klkmbd8VoMQc.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/OYrD2tBIBPvoJXiIHnLoOXnY9M.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/JeYwfuaPfZHQhEG8U5gtPDZ7WQ.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/GrgcKwrN6d3Uz8EwcLHZxwEfC4.woff2",
					weight: "400",
				},
				{
					family: "Inter",
					source: "framer",
					style: "normal",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/b6Y37FthZeALduNqHicBT6FutY.woff2",
					weight: "400",
				},
				{
					family: "FONTSPRING DEMO - Allotrope Bold",
					source: "custom",
					url: "https://framerusercontent.com/assets/Mx13lorsA1BvkA7M6dsWMn8o9U.woff2",
				},
			],
		},
		...AnimatedNumberCounterFonts,
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);

// virtual:card/features-2
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [
	{
		id: "bvzy1WeYw",
		name: "English",
		slug: "en",
		code: "en",
	},
];
var defaultResponsiveVariants = {
	base: "sVo4L48mS",
	xl: "SmW3Sw4UK",
};
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"f7de02364badfaa19730b887fe40769babb999f1ad18406989d28f58b996eb79"
			}
			locale={locale}
			locales={locales}
		>
			{jsx(stdin_default, {
				...rest,
			})}
		</ContextProviders>
	);
}
/**
 * @type {import("unframer").UnframerBreakpoint}
 * Represents a responsive breakpoint for unframer.
 */

/**
 * @typedef VariantsMap
 * Partial record of UnframerBreakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in UnframerBreakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders Features2FramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			routes={routes}
			framerSiteId={
				"f7de02364badfaa19730b887fe40769babb999f1ad18406989d28f58b996eb79"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				Component={stdin_default}
				variants={defaultResponsiveVariants}
				{...rest}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, stdin_default);
var features_2_default = ComponentWithRoot;
export { features_2_default as default };
